// Code generated by ent, DO NOT EDIT.

package resourcepool

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/VMware-AI/agent-platform-backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldName, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldEndpoint, v))
}

// SecretRef applies equality check predicate on the "secret_ref" field. It's identical to SecretRefEQ.
func SecretRef(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldSecretRef, v))
}

// DatacenterCount applies equality check predicate on the "datacenter_count" field. It's identical to DatacenterCountEQ.
func DatacenterCount(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldDatacenterCount, v))
}

// ClusterCount applies equality check predicate on the "cluster_count" field. It's identical to ClusterCountEQ.
func ClusterCount(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldClusterCount, v))
}

// HostCount applies equality check predicate on the "host_count" field. It's identical to HostCountEQ.
func HostCount(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldHostCount, v))
}

// VMCount applies equality check predicate on the "vm_count" field. It's identical to VMCountEQ.
func VMCount(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldVMCount, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldTenantID, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldEnvironmentID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldContainsFold(FieldName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldKind, vs...))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldContainsFold(FieldEndpoint, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldStatus, vs...))
}

// SecretRefEQ applies the EQ predicate on the "secret_ref" field.
func SecretRefEQ(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldSecretRef, v))
}

// SecretRefNEQ applies the NEQ predicate on the "secret_ref" field.
func SecretRefNEQ(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldSecretRef, v))
}

// SecretRefIn applies the In predicate on the "secret_ref" field.
func SecretRefIn(vs ...string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldSecretRef, vs...))
}

// SecretRefNotIn applies the NotIn predicate on the "secret_ref" field.
func SecretRefNotIn(vs ...string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldSecretRef, vs...))
}

// SecretRefGT applies the GT predicate on the "secret_ref" field.
func SecretRefGT(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldSecretRef, v))
}

// SecretRefGTE applies the GTE predicate on the "secret_ref" field.
func SecretRefGTE(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldSecretRef, v))
}

// SecretRefLT applies the LT predicate on the "secret_ref" field.
func SecretRefLT(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldSecretRef, v))
}

// SecretRefLTE applies the LTE predicate on the "secret_ref" field.
func SecretRefLTE(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldSecretRef, v))
}

// SecretRefContains applies the Contains predicate on the "secret_ref" field.
func SecretRefContains(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldContains(FieldSecretRef, v))
}

// SecretRefHasPrefix applies the HasPrefix predicate on the "secret_ref" field.
func SecretRefHasPrefix(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldHasPrefix(FieldSecretRef, v))
}

// SecretRefHasSuffix applies the HasSuffix predicate on the "secret_ref" field.
func SecretRefHasSuffix(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldHasSuffix(FieldSecretRef, v))
}

// SecretRefIsNil applies the IsNil predicate on the "secret_ref" field.
func SecretRefIsNil() predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIsNull(FieldSecretRef))
}

// SecretRefNotNil applies the NotNil predicate on the "secret_ref" field.
func SecretRefNotNil() predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotNull(FieldSecretRef))
}

// SecretRefEqualFold applies the EqualFold predicate on the "secret_ref" field.
func SecretRefEqualFold(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEqualFold(FieldSecretRef, v))
}

// SecretRefContainsFold applies the ContainsFold predicate on the "secret_ref" field.
func SecretRefContainsFold(v string) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldContainsFold(FieldSecretRef, v))
}

// DatacenterCountEQ applies the EQ predicate on the "datacenter_count" field.
func DatacenterCountEQ(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldDatacenterCount, v))
}

// DatacenterCountNEQ applies the NEQ predicate on the "datacenter_count" field.
func DatacenterCountNEQ(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldDatacenterCount, v))
}

// DatacenterCountIn applies the In predicate on the "datacenter_count" field.
func DatacenterCountIn(vs ...int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldDatacenterCount, vs...))
}

// DatacenterCountNotIn applies the NotIn predicate on the "datacenter_count" field.
func DatacenterCountNotIn(vs ...int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldDatacenterCount, vs...))
}

// DatacenterCountGT applies the GT predicate on the "datacenter_count" field.
func DatacenterCountGT(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldDatacenterCount, v))
}

// DatacenterCountGTE applies the GTE predicate on the "datacenter_count" field.
func DatacenterCountGTE(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldDatacenterCount, v))
}

// DatacenterCountLT applies the LT predicate on the "datacenter_count" field.
func DatacenterCountLT(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldDatacenterCount, v))
}

// DatacenterCountLTE applies the LTE predicate on the "datacenter_count" field.
func DatacenterCountLTE(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldDatacenterCount, v))
}

// ClusterCountEQ applies the EQ predicate on the "cluster_count" field.
func ClusterCountEQ(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldClusterCount, v))
}

// ClusterCountNEQ applies the NEQ predicate on the "cluster_count" field.
func ClusterCountNEQ(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldClusterCount, v))
}

// ClusterCountIn applies the In predicate on the "cluster_count" field.
func ClusterCountIn(vs ...int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldClusterCount, vs...))
}

// ClusterCountNotIn applies the NotIn predicate on the "cluster_count" field.
func ClusterCountNotIn(vs ...int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldClusterCount, vs...))
}

// ClusterCountGT applies the GT predicate on the "cluster_count" field.
func ClusterCountGT(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldClusterCount, v))
}

// ClusterCountGTE applies the GTE predicate on the "cluster_count" field.
func ClusterCountGTE(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldClusterCount, v))
}

// ClusterCountLT applies the LT predicate on the "cluster_count" field.
func ClusterCountLT(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldClusterCount, v))
}

// ClusterCountLTE applies the LTE predicate on the "cluster_count" field.
func ClusterCountLTE(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldClusterCount, v))
}

// HostCountEQ applies the EQ predicate on the "host_count" field.
func HostCountEQ(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldHostCount, v))
}

// HostCountNEQ applies the NEQ predicate on the "host_count" field.
func HostCountNEQ(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldHostCount, v))
}

// HostCountIn applies the In predicate on the "host_count" field.
func HostCountIn(vs ...int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldHostCount, vs...))
}

// HostCountNotIn applies the NotIn predicate on the "host_count" field.
func HostCountNotIn(vs ...int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldHostCount, vs...))
}

// HostCountGT applies the GT predicate on the "host_count" field.
func HostCountGT(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldHostCount, v))
}

// HostCountGTE applies the GTE predicate on the "host_count" field.
func HostCountGTE(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldHostCount, v))
}

// HostCountLT applies the LT predicate on the "host_count" field.
func HostCountLT(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldHostCount, v))
}

// HostCountLTE applies the LTE predicate on the "host_count" field.
func HostCountLTE(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldHostCount, v))
}

// VMCountEQ applies the EQ predicate on the "vm_count" field.
func VMCountEQ(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldVMCount, v))
}

// VMCountNEQ applies the NEQ predicate on the "vm_count" field.
func VMCountNEQ(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldVMCount, v))
}

// VMCountIn applies the In predicate on the "vm_count" field.
func VMCountIn(vs ...int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldVMCount, vs...))
}

// VMCountNotIn applies the NotIn predicate on the "vm_count" field.
func VMCountNotIn(vs ...int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldVMCount, vs...))
}

// VMCountGT applies the GT predicate on the "vm_count" field.
func VMCountGT(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldVMCount, v))
}

// VMCountGTE applies the GTE predicate on the "vm_count" field.
func VMCountGTE(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldVMCount, v))
}

// VMCountLT applies the LT predicate on the "vm_count" field.
func VMCountLT(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldVMCount, v))
}

// VMCountLTE applies the LTE predicate on the "vm_count" field.
func VMCountLTE(v int) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldVMCount, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotNull(FieldTenantID))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v uuid.UUID) predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.ResourcePool {
	return predicate.ResourcePool(sql.FieldNotNull(FieldEnvironmentID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResourcePool) predicate.ResourcePool {
	return predicate.ResourcePool(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResourcePool) predicate.ResourcePool {
	return predicate.ResourcePool(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResourcePool) predicate.ResourcePool {
	return predicate.ResourcePool(sql.NotPredicates(p))
}
