// Code generated by ent, DO NOT EDIT.

package modelroute

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the modelroute type in the database.
	Label = "model_route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldModelAlias holds the string denoting the model_alias field in the database.
	FieldModelAlias = "model_alias"
	// FieldModelGatewayID holds the string denoting the model_gateway_id field in the database.
	FieldModelGatewayID = "model_gateway_id"
	// FieldUpstreams holds the string denoting the upstreams field in the database.
	FieldUpstreams = "upstreams"
	// FieldStrategy holds the string denoting the strategy field in the database.
	FieldStrategy = "strategy"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldFallbacks holds the string denoting the fallbacks field in the database.
	FieldFallbacks = "fallbacks"
	// FieldContextWindowFallbacks holds the string denoting the context_window_fallbacks field in the database.
	FieldContextWindowFallbacks = "context_window_fallbacks"
	// FieldContentPolicyFallbacks holds the string denoting the content_policy_fallbacks field in the database.
	FieldContentPolicyFallbacks = "content_policy_fallbacks"
	// Table holds the table name of the modelroute in the database.
	Table = "model_routes"
)

// Columns holds all SQL columns for modelroute fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldModelAlias,
	FieldModelGatewayID,
	FieldUpstreams,
	FieldStrategy,
	FieldEnabled,
	FieldFallbacks,
	FieldContextWindowFallbacks,
	FieldContentPolicyFallbacks,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ModelAliasValidator is a validator for the "model_alias" field. It is called by the builders before save.
	ModelAliasValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Strategy defines the type for the "strategy" enum field.
type Strategy string

// StrategySIMPLE_SHUFFLE is the default value of the Strategy enum.
const DefaultStrategy = StrategySIMPLE_SHUFFLE

// Strategy values.
const (
	StrategySIMPLE_SHUFFLE         Strategy = "SIMPLE_SHUFFLE"
	StrategyLEAST_BUSY             Strategy = "LEAST_BUSY"
	StrategyLATENCY_BASED_ROUTING  Strategy = "LATENCY_BASED_ROUTING"
	StrategyUSAGE_BASED_ROUTING_V2 Strategy = "USAGE_BASED_ROUTING_V2"
	StrategyCOST_BASED_ROUTING     Strategy = "COST_BASED_ROUTING"
)

func (s Strategy) String() string {
	return string(s)
}

// StrategyValidator is a validator for the "strategy" field enum values. It is called by the builders before save.
func StrategyValidator(s Strategy) error {
	switch s {
	case StrategySIMPLE_SHUFFLE, StrategyLEAST_BUSY, StrategyLATENCY_BASED_ROUTING, StrategyUSAGE_BASED_ROUTING_V2, StrategyCOST_BASED_ROUTING:
		return nil
	default:
		return fmt.Errorf("modelroute: invalid enum value for strategy field: %q", s)
	}
}

// OrderOption defines the ordering options for the ModelRoute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByModelAlias orders the results by the model_alias field.
func ByModelAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelAlias, opts...).ToFunc()
}

// ByModelGatewayID orders the results by the model_gateway_id field.
func ByModelGatewayID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelGatewayID, opts...).ToFunc()
}

// ByStrategy orders the results by the strategy field.
func ByStrategy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategy, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}
