// Code generated by ent, DO NOT EDIT.

package agent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/VMware-AI/agent-platform-backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldName, v))
}

// AgentType applies equality check predicate on the "agent_type" field. It's identical to AgentTypeEQ.
func AgentType(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldAgentType, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldOwnerUserID, v))
}

// VMRef applies equality check predicate on the "vm_ref" field. It's identical to VMRefEQ.
func VMRef(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldVMRef, v))
}

// ConfigID applies equality check predicate on the "config_id" field. It's identical to ConfigIDEQ.
func ConfigID(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldConfigID, v))
}

// VirtualKeyID applies equality check predicate on the "virtual_key_id" field. It's identical to VirtualKeyIDEQ.
func VirtualKeyID(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldVirtualKeyID, v))
}

// ResourcePoolID applies equality check predicate on the "resource_pool_id" field. It's identical to ResourcePoolIDEQ.
func ResourcePoolID(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldResourcePoolID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldName, v))
}

// AgentTypeEQ applies the EQ predicate on the "agent_type" field.
func AgentTypeEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldAgentType, v))
}

// AgentTypeNEQ applies the NEQ predicate on the "agent_type" field.
func AgentTypeNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldAgentType, v))
}

// AgentTypeIn applies the In predicate on the "agent_type" field.
func AgentTypeIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldAgentType, vs...))
}

// AgentTypeNotIn applies the NotIn predicate on the "agent_type" field.
func AgentTypeNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldAgentType, vs...))
}

// AgentTypeGT applies the GT predicate on the "agent_type" field.
func AgentTypeGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldAgentType, v))
}

// AgentTypeGTE applies the GTE predicate on the "agent_type" field.
func AgentTypeGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldAgentType, v))
}

// AgentTypeLT applies the LT predicate on the "agent_type" field.
func AgentTypeLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldAgentType, v))
}

// AgentTypeLTE applies the LTE predicate on the "agent_type" field.
func AgentTypeLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldAgentType, v))
}

// AgentTypeContains applies the Contains predicate on the "agent_type" field.
func AgentTypeContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldAgentType, v))
}

// AgentTypeHasPrefix applies the HasPrefix predicate on the "agent_type" field.
func AgentTypeHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldAgentType, v))
}

// AgentTypeHasSuffix applies the HasSuffix predicate on the "agent_type" field.
func AgentTypeHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldAgentType, v))
}

// AgentTypeEqualFold applies the EqualFold predicate on the "agent_type" field.
func AgentTypeEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldAgentType, v))
}

// AgentTypeContainsFold applies the ContainsFold predicate on the "agent_type" field.
func AgentTypeContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldAgentType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldStatus, vs...))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldOwnerUserID, v))
}

// VMRefEQ applies the EQ predicate on the "vm_ref" field.
func VMRefEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldVMRef, v))
}

// VMRefNEQ applies the NEQ predicate on the "vm_ref" field.
func VMRefNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldVMRef, v))
}

// VMRefIn applies the In predicate on the "vm_ref" field.
func VMRefIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldVMRef, vs...))
}

// VMRefNotIn applies the NotIn predicate on the "vm_ref" field.
func VMRefNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldVMRef, vs...))
}

// VMRefGT applies the GT predicate on the "vm_ref" field.
func VMRefGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldVMRef, v))
}

// VMRefGTE applies the GTE predicate on the "vm_ref" field.
func VMRefGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldVMRef, v))
}

// VMRefLT applies the LT predicate on the "vm_ref" field.
func VMRefLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldVMRef, v))
}

// VMRefLTE applies the LTE predicate on the "vm_ref" field.
func VMRefLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldVMRef, v))
}

// VMRefContains applies the Contains predicate on the "vm_ref" field.
func VMRefContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldVMRef, v))
}

// VMRefHasPrefix applies the HasPrefix predicate on the "vm_ref" field.
func VMRefHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldVMRef, v))
}

// VMRefHasSuffix applies the HasSuffix predicate on the "vm_ref" field.
func VMRefHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldVMRef, v))
}

// VMRefIsNil applies the IsNil predicate on the "vm_ref" field.
func VMRefIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldVMRef))
}

// VMRefNotNil applies the NotNil predicate on the "vm_ref" field.
func VMRefNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldVMRef))
}

// VMRefEqualFold applies the EqualFold predicate on the "vm_ref" field.
func VMRefEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldVMRef, v))
}

// VMRefContainsFold applies the ContainsFold predicate on the "vm_ref" field.
func VMRefContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldVMRef, v))
}

// ConfigIDEQ applies the EQ predicate on the "config_id" field.
func ConfigIDEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldConfigID, v))
}

// ConfigIDNEQ applies the NEQ predicate on the "config_id" field.
func ConfigIDNEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldConfigID, v))
}

// ConfigIDIn applies the In predicate on the "config_id" field.
func ConfigIDIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldConfigID, vs...))
}

// ConfigIDNotIn applies the NotIn predicate on the "config_id" field.
func ConfigIDNotIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldConfigID, vs...))
}

// ConfigIDGT applies the GT predicate on the "config_id" field.
func ConfigIDGT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldConfigID, v))
}

// ConfigIDGTE applies the GTE predicate on the "config_id" field.
func ConfigIDGTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldConfigID, v))
}

// ConfigIDLT applies the LT predicate on the "config_id" field.
func ConfigIDLT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldConfigID, v))
}

// ConfigIDLTE applies the LTE predicate on the "config_id" field.
func ConfigIDLTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldConfigID, v))
}

// ConfigIDIsNil applies the IsNil predicate on the "config_id" field.
func ConfigIDIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldConfigID))
}

// ConfigIDNotNil applies the NotNil predicate on the "config_id" field.
func ConfigIDNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldConfigID))
}

// VirtualKeyIDEQ applies the EQ predicate on the "virtual_key_id" field.
func VirtualKeyIDEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldVirtualKeyID, v))
}

// VirtualKeyIDNEQ applies the NEQ predicate on the "virtual_key_id" field.
func VirtualKeyIDNEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldVirtualKeyID, v))
}

// VirtualKeyIDIn applies the In predicate on the "virtual_key_id" field.
func VirtualKeyIDIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldVirtualKeyID, vs...))
}

// VirtualKeyIDNotIn applies the NotIn predicate on the "virtual_key_id" field.
func VirtualKeyIDNotIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldVirtualKeyID, vs...))
}

// VirtualKeyIDGT applies the GT predicate on the "virtual_key_id" field.
func VirtualKeyIDGT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldVirtualKeyID, v))
}

// VirtualKeyIDGTE applies the GTE predicate on the "virtual_key_id" field.
func VirtualKeyIDGTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldVirtualKeyID, v))
}

// VirtualKeyIDLT applies the LT predicate on the "virtual_key_id" field.
func VirtualKeyIDLT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldVirtualKeyID, v))
}

// VirtualKeyIDLTE applies the LTE predicate on the "virtual_key_id" field.
func VirtualKeyIDLTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldVirtualKeyID, v))
}

// VirtualKeyIDIsNil applies the IsNil predicate on the "virtual_key_id" field.
func VirtualKeyIDIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldVirtualKeyID))
}

// VirtualKeyIDNotNil applies the NotNil predicate on the "virtual_key_id" field.
func VirtualKeyIDNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldVirtualKeyID))
}

// ResourcePoolIDEQ applies the EQ predicate on the "resource_pool_id" field.
func ResourcePoolIDEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldResourcePoolID, v))
}

// ResourcePoolIDNEQ applies the NEQ predicate on the "resource_pool_id" field.
func ResourcePoolIDNEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldResourcePoolID, v))
}

// ResourcePoolIDIn applies the In predicate on the "resource_pool_id" field.
func ResourcePoolIDIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldResourcePoolID, vs...))
}

// ResourcePoolIDNotIn applies the NotIn predicate on the "resource_pool_id" field.
func ResourcePoolIDNotIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldResourcePoolID, vs...))
}

// ResourcePoolIDGT applies the GT predicate on the "resource_pool_id" field.
func ResourcePoolIDGT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldResourcePoolID, v))
}

// ResourcePoolIDGTE applies the GTE predicate on the "resource_pool_id" field.
func ResourcePoolIDGTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldResourcePoolID, v))
}

// ResourcePoolIDLT applies the LT predicate on the "resource_pool_id" field.
func ResourcePoolIDLT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldResourcePoolID, v))
}

// ResourcePoolIDLTE applies the LTE predicate on the "resource_pool_id" field.
func ResourcePoolIDLTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldResourcePoolID, v))
}

// ResourcePoolIDIsNil applies the IsNil predicate on the "resource_pool_id" field.
func ResourcePoolIDIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldResourcePoolID))
}

// ResourcePoolIDNotNil applies the NotNil predicate on the "resource_pool_id" field.
func ResourcePoolIDNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldResourcePoolID))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldTenantID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.NotPredicates(p))
}
