// Code generated by ent, DO NOT EDIT.

package gatewayconnection

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/VMware-AI/agent-platform-backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldName, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldEndpoint, v))
}

// MasterKeyRef applies equality check predicate on the "master_key_ref" field. It's identical to MasterKeyRefEQ.
func MasterKeyRef(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldMasterKeyRef, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldLastSyncedAt, v))
}

// BackendModelCount applies equality check predicate on the "backend_model_count" field. It's identical to BackendModelCountEQ.
func BackendModelCount(v int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldBackendModelCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldContainsFold(FieldName, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldContainsFold(FieldEndpoint, v))
}

// MasterKeyRefEQ applies the EQ predicate on the "master_key_ref" field.
func MasterKeyRefEQ(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldMasterKeyRef, v))
}

// MasterKeyRefNEQ applies the NEQ predicate on the "master_key_ref" field.
func MasterKeyRefNEQ(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldMasterKeyRef, v))
}

// MasterKeyRefIn applies the In predicate on the "master_key_ref" field.
func MasterKeyRefIn(vs ...string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldMasterKeyRef, vs...))
}

// MasterKeyRefNotIn applies the NotIn predicate on the "master_key_ref" field.
func MasterKeyRefNotIn(vs ...string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldMasterKeyRef, vs...))
}

// MasterKeyRefGT applies the GT predicate on the "master_key_ref" field.
func MasterKeyRefGT(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGT(FieldMasterKeyRef, v))
}

// MasterKeyRefGTE applies the GTE predicate on the "master_key_ref" field.
func MasterKeyRefGTE(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGTE(FieldMasterKeyRef, v))
}

// MasterKeyRefLT applies the LT predicate on the "master_key_ref" field.
func MasterKeyRefLT(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLT(FieldMasterKeyRef, v))
}

// MasterKeyRefLTE applies the LTE predicate on the "master_key_ref" field.
func MasterKeyRefLTE(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLTE(FieldMasterKeyRef, v))
}

// MasterKeyRefContains applies the Contains predicate on the "master_key_ref" field.
func MasterKeyRefContains(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldContains(FieldMasterKeyRef, v))
}

// MasterKeyRefHasPrefix applies the HasPrefix predicate on the "master_key_ref" field.
func MasterKeyRefHasPrefix(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldHasPrefix(FieldMasterKeyRef, v))
}

// MasterKeyRefHasSuffix applies the HasSuffix predicate on the "master_key_ref" field.
func MasterKeyRefHasSuffix(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldHasSuffix(FieldMasterKeyRef, v))
}

// MasterKeyRefIsNil applies the IsNil predicate on the "master_key_ref" field.
func MasterKeyRefIsNil() predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIsNull(FieldMasterKeyRef))
}

// MasterKeyRefNotNil applies the NotNil predicate on the "master_key_ref" field.
func MasterKeyRefNotNil() predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotNull(FieldMasterKeyRef))
}

// MasterKeyRefEqualFold applies the EqualFold predicate on the "master_key_ref" field.
func MasterKeyRefEqualFold(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEqualFold(FieldMasterKeyRef, v))
}

// MasterKeyRefContainsFold applies the ContainsFold predicate on the "master_key_ref" field.
func MasterKeyRefContainsFold(v string) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldContainsFold(FieldMasterKeyRef, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotNull(FieldLastSyncedAt))
}

// BackendModelCountEQ applies the EQ predicate on the "backend_model_count" field.
func BackendModelCountEQ(v int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldBackendModelCount, v))
}

// BackendModelCountNEQ applies the NEQ predicate on the "backend_model_count" field.
func BackendModelCountNEQ(v int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldBackendModelCount, v))
}

// BackendModelCountIn applies the In predicate on the "backend_model_count" field.
func BackendModelCountIn(vs ...int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldBackendModelCount, vs...))
}

// BackendModelCountNotIn applies the NotIn predicate on the "backend_model_count" field.
func BackendModelCountNotIn(vs ...int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldBackendModelCount, vs...))
}

// BackendModelCountGT applies the GT predicate on the "backend_model_count" field.
func BackendModelCountGT(v int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGT(FieldBackendModelCount, v))
}

// BackendModelCountGTE applies the GTE predicate on the "backend_model_count" field.
func BackendModelCountGTE(v int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldGTE(FieldBackendModelCount, v))
}

// BackendModelCountLT applies the LT predicate on the "backend_model_count" field.
func BackendModelCountLT(v int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLT(FieldBackendModelCount, v))
}

// BackendModelCountLTE applies the LTE predicate on the "backend_model_count" field.
func BackendModelCountLTE(v int) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldLTE(FieldBackendModelCount, v))
}

// BackendModelCountIsNil applies the IsNil predicate on the "backend_model_count" field.
func BackendModelCountIsNil() predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIsNull(FieldBackendModelCount))
}

// BackendModelCountNotNil applies the NotNil predicate on the "backend_model_count" field.
func BackendModelCountNotNil() predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotNull(FieldBackendModelCount))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldStatus, vs...))
}

// LoadBalanceStrategyEQ applies the EQ predicate on the "load_balance_strategy" field.
func LoadBalanceStrategyEQ(v LoadBalanceStrategy) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldEQ(FieldLoadBalanceStrategy, v))
}

// LoadBalanceStrategyNEQ applies the NEQ predicate on the "load_balance_strategy" field.
func LoadBalanceStrategyNEQ(v LoadBalanceStrategy) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNEQ(FieldLoadBalanceStrategy, v))
}

// LoadBalanceStrategyIn applies the In predicate on the "load_balance_strategy" field.
func LoadBalanceStrategyIn(vs ...LoadBalanceStrategy) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldIn(FieldLoadBalanceStrategy, vs...))
}

// LoadBalanceStrategyNotIn applies the NotIn predicate on the "load_balance_strategy" field.
func LoadBalanceStrategyNotIn(vs ...LoadBalanceStrategy) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.FieldNotIn(FieldLoadBalanceStrategy, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GatewayConnection) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GatewayConnection) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GatewayConnection) predicate.GatewayConnection {
	return predicate.GatewayConnection(sql.NotPredicates(p))
}
