// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/VMware-AI/agent-platform-backend/ent/agentheartbeat"
	"github.com/VMware-AI/agent-platform-backend/ent/predicate"
	"github.com/google/uuid"
)

// AgentHeartbeatUpdate is the builder for updating AgentHeartbeat entities.
type AgentHeartbeatUpdate struct {
	config
	hooks     []Hook
	mutation  *AgentHeartbeatMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AgentHeartbeatUpdate builder.
func (_u *AgentHeartbeatUpdate) Where(ps ...predicate.AgentHeartbeat) *AgentHeartbeatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentHeartbeatUpdate) SetAgentID(v uuid.UUID) *AgentHeartbeatUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentHeartbeatUpdate) SetNillableAgentID(v *uuid.UUID) *AgentHeartbeatUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetReportedAt sets the "reported_at" field.
func (_u *AgentHeartbeatUpdate) SetReportedAt(v time.Time) *AgentHeartbeatUpdate {
	_u.mutation.SetReportedAt(v)
	return _u
}

// SetNillableReportedAt sets the "reported_at" field if the given value is not nil.
func (_u *AgentHeartbeatUpdate) SetNillableReportedAt(v *time.Time) *AgentHeartbeatUpdate {
	if v != nil {
		_u.SetReportedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentHeartbeatUpdate) SetStatus(v agentheartbeat.Status) *AgentHeartbeatUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentHeartbeatUpdate) SetNillableStatus(v *agentheartbeat.Status) *AgentHeartbeatUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAgentVersion sets the "agent_version" field.
func (_u *AgentHeartbeatUpdate) SetAgentVersion(v string) *AgentHeartbeatUpdate {
	_u.mutation.SetAgentVersion(v)
	return _u
}

// SetNillableAgentVersion sets the "agent_version" field if the given value is not nil.
func (_u *AgentHeartbeatUpdate) SetNillableAgentVersion(v *string) *AgentHeartbeatUpdate {
	if v != nil {
		_u.SetAgentVersion(*v)
	}
	return _u
}

// ClearAgentVersion clears the value of the "agent_version" field.
func (_u *AgentHeartbeatUpdate) ClearAgentVersion() *AgentHeartbeatUpdate {
	_u.mutation.ClearAgentVersion()
	return _u
}

// SetRotationState sets the "rotation_state" field.
func (_u *AgentHeartbeatUpdate) SetRotationState(v agentheartbeat.RotationState) *AgentHeartbeatUpdate {
	_u.mutation.SetRotationState(v)
	return _u
}

// SetNillableRotationState sets the "rotation_state" field if the given value is not nil.
func (_u *AgentHeartbeatUpdate) SetNillableRotationState(v *agentheartbeat.RotationState) *AgentHeartbeatUpdate {
	if v != nil {
		_u.SetRotationState(*v)
	}
	return _u
}

// ClearRotationState clears the value of the "rotation_state" field.
func (_u *AgentHeartbeatUpdate) ClearRotationState() *AgentHeartbeatUpdate {
	_u.mutation.ClearRotationState()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AgentHeartbeatUpdate) SetDetail(v map[string]interface{}) *AgentHeartbeatUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *AgentHeartbeatUpdate) ClearDetail() *AgentHeartbeatUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// Mutation returns the AgentHeartbeatMutation object of the builder.
func (_u *AgentHeartbeatUpdate) Mutation() *AgentHeartbeatMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentHeartbeatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentHeartbeatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentHeartbeatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentHeartbeatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentHeartbeatUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := agentheartbeat.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentHeartbeat.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RotationState(); ok {
		if err := agentheartbeat.RotationStateValidator(v); err != nil {
			return &ValidationError{Name: "rotation_state", err: fmt.Errorf(`ent: validator failed for field "AgentHeartbeat.rotation_state": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentHeartbeatUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentHeartbeatUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentHeartbeatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentheartbeat.Table, agentheartbeat.Columns, sqlgraph.NewFieldSpec(agentheartbeat.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(agentheartbeat.FieldAgentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ReportedAt(); ok {
		_spec.SetField(agentheartbeat.FieldReportedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentheartbeat.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AgentVersion(); ok {
		_spec.SetField(agentheartbeat.FieldAgentVersion, field.TypeString, value)
	}
	if _u.mutation.AgentVersionCleared() {
		_spec.ClearField(agentheartbeat.FieldAgentVersion, field.TypeString)
	}
	if value, ok := _u.mutation.RotationState(); ok {
		_spec.SetField(agentheartbeat.FieldRotationState, field.TypeEnum, value)
	}
	if _u.mutation.RotationStateCleared() {
		_spec.ClearField(agentheartbeat.FieldRotationState, field.TypeEnum)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(agentheartbeat.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(agentheartbeat.FieldDetail, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentheartbeat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentHeartbeatUpdateOne is the builder for updating a single AgentHeartbeat entity.
type AgentHeartbeatUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AgentHeartbeatMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentHeartbeatUpdateOne) SetAgentID(v uuid.UUID) *AgentHeartbeatUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentHeartbeatUpdateOne) SetNillableAgentID(v *uuid.UUID) *AgentHeartbeatUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetReportedAt sets the "reported_at" field.
func (_u *AgentHeartbeatUpdateOne) SetReportedAt(v time.Time) *AgentHeartbeatUpdateOne {
	_u.mutation.SetReportedAt(v)
	return _u
}

// SetNillableReportedAt sets the "reported_at" field if the given value is not nil.
func (_u *AgentHeartbeatUpdateOne) SetNillableReportedAt(v *time.Time) *AgentHeartbeatUpdateOne {
	if v != nil {
		_u.SetReportedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentHeartbeatUpdateOne) SetStatus(v agentheartbeat.Status) *AgentHeartbeatUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentHeartbeatUpdateOne) SetNillableStatus(v *agentheartbeat.Status) *AgentHeartbeatUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAgentVersion sets the "agent_version" field.
func (_u *AgentHeartbeatUpdateOne) SetAgentVersion(v string) *AgentHeartbeatUpdateOne {
	_u.mutation.SetAgentVersion(v)
	return _u
}

// SetNillableAgentVersion sets the "agent_version" field if the given value is not nil.
func (_u *AgentHeartbeatUpdateOne) SetNillableAgentVersion(v *string) *AgentHeartbeatUpdateOne {
	if v != nil {
		_u.SetAgentVersion(*v)
	}
	return _u
}

// ClearAgentVersion clears the value of the "agent_version" field.
func (_u *AgentHeartbeatUpdateOne) ClearAgentVersion() *AgentHeartbeatUpdateOne {
	_u.mutation.ClearAgentVersion()
	return _u
}

// SetRotationState sets the "rotation_state" field.
func (_u *AgentHeartbeatUpdateOne) SetRotationState(v agentheartbeat.RotationState) *AgentHeartbeatUpdateOne {
	_u.mutation.SetRotationState(v)
	return _u
}

// SetNillableRotationState sets the "rotation_state" field if the given value is not nil.
func (_u *AgentHeartbeatUpdateOne) SetNillableRotationState(v *agentheartbeat.RotationState) *AgentHeartbeatUpdateOne {
	if v != nil {
		_u.SetRotationState(*v)
	}
	return _u
}

// ClearRotationState clears the value of the "rotation_state" field.
func (_u *AgentHeartbeatUpdateOne) ClearRotationState() *AgentHeartbeatUpdateOne {
	_u.mutation.ClearRotationState()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AgentHeartbeatUpdateOne) SetDetail(v map[string]interface{}) *AgentHeartbeatUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *AgentHeartbeatUpdateOne) ClearDetail() *AgentHeartbeatUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// Mutation returns the AgentHeartbeatMutation object of the builder.
func (_u *AgentHeartbeatUpdateOne) Mutation() *AgentHeartbeatMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentHeartbeatUpdate builder.
func (_u *AgentHeartbeatUpdateOne) Where(ps ...predicate.AgentHeartbeat) *AgentHeartbeatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentHeartbeatUpdateOne) Select(field string, fields ...string) *AgentHeartbeatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentHeartbeat entity.
func (_u *AgentHeartbeatUpdateOne) Save(ctx context.Context) (*AgentHeartbeat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentHeartbeatUpdateOne) SaveX(ctx context.Context) *AgentHeartbeat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentHeartbeatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentHeartbeatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentHeartbeatUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := agentheartbeat.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentHeartbeat.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RotationState(); ok {
		if err := agentheartbeat.RotationStateValidator(v); err != nil {
			return &ValidationError{Name: "rotation_state", err: fmt.Errorf(`ent: validator failed for field "AgentHeartbeat.rotation_state": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AgentHeartbeatUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AgentHeartbeatUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AgentHeartbeatUpdateOne) sqlSave(ctx context.Context) (_node *AgentHeartbeat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentheartbeat.Table, agentheartbeat.Columns, sqlgraph.NewFieldSpec(agentheartbeat.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentHeartbeat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentheartbeat.FieldID)
		for _, f := range fields {
			if !agentheartbeat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentheartbeat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(agentheartbeat.FieldAgentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ReportedAt(); ok {
		_spec.SetField(agentheartbeat.FieldReportedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentheartbeat.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AgentVersion(); ok {
		_spec.SetField(agentheartbeat.FieldAgentVersion, field.TypeString, value)
	}
	if _u.mutation.AgentVersionCleared() {
		_spec.ClearField(agentheartbeat.FieldAgentVersion, field.TypeString)
	}
	if value, ok := _u.mutation.RotationState(); ok {
		_spec.SetField(agentheartbeat.FieldRotationState, field.TypeEnum, value)
	}
	if _u.mutation.RotationStateCleared() {
		_spec.ClearField(agentheartbeat.FieldRotationState, field.TypeEnum)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(agentheartbeat.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(agentheartbeat.FieldDetail, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AgentHeartbeat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentheartbeat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
