// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/VMware-AI/agent-platform-backend/ent/gatewayconnection"
	"github.com/google/uuid"
)

// GatewayConnection is the model entity for the GatewayConnection schema.
type GatewayConnection struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// MasterKeyRef holds the value of the "master_key_ref" field.
	MasterKeyRef string `json:"master_key_ref,omitempty"`
	// Status holds the value of the "status" field.
	Status gatewayconnection.Status `json:"status,omitempty"`
	// LoadBalanceStrategy holds the value of the "load_balance_strategy" field.
	LoadBalanceStrategy gatewayconnection.LoadBalanceStrategy `json:"load_balance_strategy,omitempty"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GatewayConnection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gatewayconnection.FieldName, gatewayconnection.FieldEndpoint, gatewayconnection.FieldMasterKeyRef, gatewayconnection.FieldStatus, gatewayconnection.FieldLoadBalanceStrategy:
			values[i] = new(sql.NullString)
		case gatewayconnection.FieldCreatedAt, gatewayconnection.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case gatewayconnection.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GatewayConnection fields.
func (_m *GatewayConnection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gatewayconnection.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case gatewayconnection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gatewayconnection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case gatewayconnection.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case gatewayconnection.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case gatewayconnection.FieldMasterKeyRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field master_key_ref", values[i])
			} else if value.Valid {
				_m.MasterKeyRef = value.String
			}
		case gatewayconnection.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = gatewayconnection.Status(value.String)
			}
		case gatewayconnection.FieldLoadBalanceStrategy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field load_balance_strategy", values[i])
			} else if value.Valid {
				_m.LoadBalanceStrategy = gatewayconnection.LoadBalanceStrategy(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GatewayConnection.
// This includes values selected through modifiers, order, etc.
func (_m *GatewayConnection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GatewayConnection.
// Note that you need to call GatewayConnection.Unwrap() before calling this method if this GatewayConnection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GatewayConnection) Update() *GatewayConnectionUpdateOne {
	return NewGatewayConnectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GatewayConnection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GatewayConnection) Unwrap() *GatewayConnection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GatewayConnection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GatewayConnection) String() string {
	var builder strings.Builder
	builder.WriteString("GatewayConnection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("master_key_ref=")
	builder.WriteString(_m.MasterKeyRef)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("load_balance_strategy=")
	builder.WriteString(fmt.Sprintf("%v", _m.LoadBalanceStrategy))
	builder.WriteByte(')')
	return builder.String()
}

// GatewayConnections is a parsable slice of GatewayConnection.
type GatewayConnections []*GatewayConnection
