// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/VMware-AI/agent-platform-backend/ent/ovatemplatefamily"
	"github.com/VMware-AI/agent-platform-backend/ent/ovatemplateversion"
	"github.com/google/uuid"
)

// OvaTemplateFamilyCreate is the builder for creating a OvaTemplateFamily entity.
type OvaTemplateFamilyCreate struct {
	config
	mutation *OvaTemplateFamilyMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OvaTemplateFamilyCreate) SetCreatedAt(v time.Time) *OvaTemplateFamilyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OvaTemplateFamilyCreate) SetNillableCreatedAt(v *time.Time) *OvaTemplateFamilyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OvaTemplateFamilyCreate) SetUpdatedAt(v time.Time) *OvaTemplateFamilyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OvaTemplateFamilyCreate) SetNillableUpdatedAt(v *time.Time) *OvaTemplateFamilyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OvaTemplateFamilyCreate) SetName(v string) *OvaTemplateFamilyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *OvaTemplateFamilyCreate) SetType(v string) *OvaTemplateFamilyCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *OvaTemplateFamilyCreate) SetDescription(v string) *OvaTemplateFamilyCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OvaTemplateFamilyCreate) SetNillableDescription(v *string) *OvaTemplateFamilyCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetTools sets the "tools" field.
func (_c *OvaTemplateFamilyCreate) SetTools(v []string) *OvaTemplateFamilyCreate {
	_c.mutation.SetTools(v)
	return _c
}

// SetSkills sets the "skills" field.
func (_c *OvaTemplateFamilyCreate) SetSkills(v []string) *OvaTemplateFamilyCreate {
	_c.mutation.SetSkills(v)
	return _c
}

// SetScenarios sets the "scenarios" field.
func (_c *OvaTemplateFamilyCreate) SetScenarios(v []string) *OvaTemplateFamilyCreate {
	_c.mutation.SetScenarios(v)
	return _c
}

// SetIconShape sets the "icon_shape" field.
func (_c *OvaTemplateFamilyCreate) SetIconShape(v string) *OvaTemplateFamilyCreate {
	_c.mutation.SetIconShape(v)
	return _c
}

// SetNillableIconShape sets the "icon_shape" field if the given value is not nil.
func (_c *OvaTemplateFamilyCreate) SetNillableIconShape(v *string) *OvaTemplateFamilyCreate {
	if v != nil {
		_c.SetIconShape(*v)
	}
	return _c
}

// SetIconColor sets the "icon_color" field.
func (_c *OvaTemplateFamilyCreate) SetIconColor(v ovatemplatefamily.IconColor) *OvaTemplateFamilyCreate {
	_c.mutation.SetIconColor(v)
	return _c
}

// SetNillableIconColor sets the "icon_color" field if the given value is not nil.
func (_c *OvaTemplateFamilyCreate) SetNillableIconColor(v *ovatemplatefamily.IconColor) *OvaTemplateFamilyCreate {
	if v != nil {
		_c.SetIconColor(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OvaTemplateFamilyCreate) SetID(v uuid.UUID) *OvaTemplateFamilyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OvaTemplateFamilyCreate) SetNillableID(v *uuid.UUID) *OvaTemplateFamilyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddVersionIDs adds the "versions" edge to the OvaTemplateVersion entity by IDs.
func (_c *OvaTemplateFamilyCreate) AddVersionIDs(ids ...uuid.UUID) *OvaTemplateFamilyCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the OvaTemplateVersion entity.
func (_c *OvaTemplateFamilyCreate) AddVersions(v ...*OvaTemplateVersion) *OvaTemplateFamilyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// Mutation returns the OvaTemplateFamilyMutation object of the builder.
func (_c *OvaTemplateFamilyCreate) Mutation() *OvaTemplateFamilyMutation {
	return _c.mutation
}

// Save creates the OvaTemplateFamily in the database.
func (_c *OvaTemplateFamilyCreate) Save(ctx context.Context) (*OvaTemplateFamily, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OvaTemplateFamilyCreate) SaveX(ctx context.Context) *OvaTemplateFamily {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OvaTemplateFamilyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OvaTemplateFamilyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OvaTemplateFamilyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ovatemplatefamily.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ovatemplatefamily.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := ovatemplatefamily.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.IconShape(); !ok {
		v := ovatemplatefamily.DefaultIconShape
		_c.mutation.SetIconShape(v)
	}
	if _, ok := _c.mutation.IconColor(); !ok {
		v := ovatemplatefamily.DefaultIconColor
		_c.mutation.SetIconColor(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := ovatemplatefamily.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OvaTemplateFamilyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OvaTemplateFamily.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OvaTemplateFamily.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OvaTemplateFamily.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ovatemplatefamily.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OvaTemplateFamily.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "OvaTemplateFamily.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := ovatemplatefamily.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OvaTemplateFamily.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "OvaTemplateFamily.description"`)}
	}
	if _, ok := _c.mutation.IconShape(); !ok {
		return &ValidationError{Name: "icon_shape", err: errors.New(`ent: missing required field "OvaTemplateFamily.icon_shape"`)}
	}
	if _, ok := _c.mutation.IconColor(); !ok {
		return &ValidationError{Name: "icon_color", err: errors.New(`ent: missing required field "OvaTemplateFamily.icon_color"`)}
	}
	if v, ok := _c.mutation.IconColor(); ok {
		if err := ovatemplatefamily.IconColorValidator(v); err != nil {
			return &ValidationError{Name: "icon_color", err: fmt.Errorf(`ent: validator failed for field "OvaTemplateFamily.icon_color": %w`, err)}
		}
	}
	return nil
}

func (_c *OvaTemplateFamilyCreate) sqlSave(ctx context.Context) (*OvaTemplateFamily, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OvaTemplateFamilyCreate) createSpec() (*OvaTemplateFamily, *sqlgraph.CreateSpec) {
	var (
		_node = &OvaTemplateFamily{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ovatemplatefamily.Table, sqlgraph.NewFieldSpec(ovatemplatefamily.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ovatemplatefamily.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ovatemplatefamily.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ovatemplatefamily.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(ovatemplatefamily.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(ovatemplatefamily.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Tools(); ok {
		_spec.SetField(ovatemplatefamily.FieldTools, field.TypeJSON, value)
		_node.Tools = value
	}
	if value, ok := _c.mutation.Skills(); ok {
		_spec.SetField(ovatemplatefamily.FieldSkills, field.TypeJSON, value)
		_node.Skills = value
	}
	if value, ok := _c.mutation.Scenarios(); ok {
		_spec.SetField(ovatemplatefamily.FieldScenarios, field.TypeJSON, value)
		_node.Scenarios = value
	}
	if value, ok := _c.mutation.IconShape(); ok {
		_spec.SetField(ovatemplatefamily.FieldIconShape, field.TypeString, value)
		_node.IconShape = value
	}
	if value, ok := _c.mutation.IconColor(); ok {
		_spec.SetField(ovatemplatefamily.FieldIconColor, field.TypeEnum, value)
		_node.IconColor = value
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ovatemplatefamily.VersionsTable,
			Columns: []string{ovatemplatefamily.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ovatemplateversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OvaTemplateFamilyCreateBulk is the builder for creating many OvaTemplateFamily entities in bulk.
type OvaTemplateFamilyCreateBulk struct {
	config
	err      error
	builders []*OvaTemplateFamilyCreate
}

// Save creates the OvaTemplateFamily entities in the database.
func (_c *OvaTemplateFamilyCreateBulk) Save(ctx context.Context) ([]*OvaTemplateFamily, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OvaTemplateFamily, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OvaTemplateFamilyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OvaTemplateFamilyCreateBulk) SaveX(ctx context.Context) []*OvaTemplateFamily {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OvaTemplateFamilyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OvaTemplateFamilyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
