// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/VMware-AI/agent-platform-backend/ent/ovatemplatefamily"
	"github.com/VMware-AI/agent-platform-backend/ent/ovatemplateversion"
	"github.com/google/uuid"
)

// OvaTemplateVersion is the model entity for the OvaTemplateVersion schema.
type OvaTemplateVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// OvaIdentifier holds the value of the "ova_identifier" field.
	OvaIdentifier string `json:"ova_identifier,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OvaTemplateVersionQuery when eager-loading is set.
	Edges                        OvaTemplateVersionEdges `json:"edges"`
	ova_template_family_versions *uuid.UUID
	selectValues                 sql.SelectValues
}

// OvaTemplateVersionEdges holds the relations/edges for other nodes in the graph.
type OvaTemplateVersionEdges struct {
	// Family holds the value of the family edge.
	Family *OvaTemplateFamily `json:"family,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FamilyOrErr returns the Family value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OvaTemplateVersionEdges) FamilyOrErr() (*OvaTemplateFamily, error) {
	if e.Family != nil {
		return e.Family, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ovatemplatefamily.Label}
	}
	return nil, &NotLoadedError{edge: "family"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OvaTemplateVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ovatemplateversion.FieldVersion, ovatemplateversion.FieldOvaIdentifier, ovatemplateversion.FieldNotes:
			values[i] = new(sql.NullString)
		case ovatemplateversion.FieldCreatedAt, ovatemplateversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case ovatemplateversion.FieldID:
			values[i] = new(uuid.UUID)
		case ovatemplateversion.ForeignKeys[0]: // ova_template_family_versions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OvaTemplateVersion fields.
func (_m *OvaTemplateVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ovatemplateversion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ovatemplateversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ovatemplateversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ovatemplateversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case ovatemplateversion.FieldOvaIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ova_identifier", values[i])
			} else if value.Valid {
				_m.OvaIdentifier = value.String
			}
		case ovatemplateversion.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case ovatemplateversion.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field ova_template_family_versions", values[i])
			} else if value.Valid {
				_m.ova_template_family_versions = new(uuid.UUID)
				*_m.ova_template_family_versions = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OvaTemplateVersion.
// This includes values selected through modifiers, order, etc.
func (_m *OvaTemplateVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFamily queries the "family" edge of the OvaTemplateVersion entity.
func (_m *OvaTemplateVersion) QueryFamily() *OvaTemplateFamilyQuery {
	return NewOvaTemplateVersionClient(_m.config).QueryFamily(_m)
}

// Update returns a builder for updating this OvaTemplateVersion.
// Note that you need to call OvaTemplateVersion.Unwrap() before calling this method if this OvaTemplateVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OvaTemplateVersion) Update() *OvaTemplateVersionUpdateOne {
	return NewOvaTemplateVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OvaTemplateVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OvaTemplateVersion) Unwrap() *OvaTemplateVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OvaTemplateVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OvaTemplateVersion) String() string {
	var builder strings.Builder
	builder.WriteString("OvaTemplateVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("ova_identifier=")
	builder.WriteString(_m.OvaIdentifier)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// OvaTemplateVersions is a parsable slice of OvaTemplateVersion.
type OvaTemplateVersions []*OvaTemplateVersion
