// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/VMware-AI/agent-platform-backend/ent/platformsecret"
)

// PlatformSecretCreate is the builder for creating a PlatformSecret entity.
type PlatformSecretCreate struct {
	config
	mutation *PlatformSecretMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlatformSecretCreate) SetCreatedAt(v time.Time) *PlatformSecretCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlatformSecretCreate) SetNillableCreatedAt(v *time.Time) *PlatformSecretCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlatformSecretCreate) SetUpdatedAt(v time.Time) *PlatformSecretCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlatformSecretCreate) SetNillableUpdatedAt(v *time.Time) *PlatformSecretCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRef sets the "ref" field.
func (_c *PlatformSecretCreate) SetRef(v string) *PlatformSecretCreate {
	_c.mutation.SetRef(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *PlatformSecretCreate) SetUsername(v string) *PlatformSecretCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *PlatformSecretCreate) SetNillableUsername(v *string) *PlatformSecretCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *PlatformSecretCreate) SetPassword(v string) *PlatformSecretCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *PlatformSecretCreate) SetNillablePassword(v *string) *PlatformSecretCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" field.
func (_c *PlatformSecretCreate) SetAPIKey(v string) *PlatformSecretCreate {
	_c.mutation.SetAPIKey(v)
	return _c
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_c *PlatformSecretCreate) SetNillableAPIKey(v *string) *PlatformSecretCreate {
	if v != nil {
		_c.SetAPIKey(*v)
	}
	return _c
}

// SetKeyID sets the "key_id" field.
func (_c *PlatformSecretCreate) SetKeyID(v string) *PlatformSecretCreate {
	_c.mutation.SetKeyID(v)
	return _c
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_c *PlatformSecretCreate) SetNillableKeyID(v *string) *PlatformSecretCreate {
	if v != nil {
		_c.SetKeyID(*v)
	}
	return _c
}

// Mutation returns the PlatformSecretMutation object of the builder.
func (_c *PlatformSecretCreate) Mutation() *PlatformSecretMutation {
	return _c.mutation
}

// Save creates the PlatformSecret in the database.
func (_c *PlatformSecretCreate) Save(ctx context.Context) (*PlatformSecret, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlatformSecretCreate) SaveX(ctx context.Context) *PlatformSecret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformSecretCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformSecretCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlatformSecretCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := platformsecret.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := platformsecret.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := platformsecret.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.Password(); !ok {
		v := platformsecret.DefaultPassword
		_c.mutation.SetPassword(v)
	}
	if _, ok := _c.mutation.APIKey(); !ok {
		v := platformsecret.DefaultAPIKey
		_c.mutation.SetAPIKey(v)
	}
	if _, ok := _c.mutation.KeyID(); !ok {
		v := platformsecret.DefaultKeyID
		_c.mutation.SetKeyID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlatformSecretCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PlatformSecret.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PlatformSecret.updated_at"`)}
	}
	if _, ok := _c.mutation.Ref(); !ok {
		return &ValidationError{Name: "ref", err: errors.New(`ent: missing required field "PlatformSecret.ref"`)}
	}
	if v, ok := _c.mutation.Ref(); ok {
		if err := platformsecret.RefValidator(v); err != nil {
			return &ValidationError{Name: "ref", err: fmt.Errorf(`ent: validator failed for field "PlatformSecret.ref": %w`, err)}
		}
	}
	return nil
}

func (_c *PlatformSecretCreate) sqlSave(ctx context.Context) (*PlatformSecret, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlatformSecretCreate) createSpec() (*PlatformSecret, *sqlgraph.CreateSpec) {
	var (
		_node = &PlatformSecret{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(platformsecret.Table, sqlgraph.NewFieldSpec(platformsecret.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(platformsecret.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(platformsecret.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Ref(); ok {
		_spec.SetField(platformsecret.FieldRef, field.TypeString, value)
		_node.Ref = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(platformsecret.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(platformsecret.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.APIKey(); ok {
		_spec.SetField(platformsecret.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := _c.mutation.KeyID(); ok {
		_spec.SetField(platformsecret.FieldKeyID, field.TypeString, value)
		_node.KeyID = value
	}
	return _node, _spec
}

// PlatformSecretCreateBulk is the builder for creating many PlatformSecret entities in bulk.
type PlatformSecretCreateBulk struct {
	config
	err      error
	builders []*PlatformSecretCreate
}

// Save creates the PlatformSecret entities in the database.
func (_c *PlatformSecretCreateBulk) Save(ctx context.Context) ([]*PlatformSecret, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlatformSecret, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformSecretMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlatformSecretCreateBulk) SaveX(ctx context.Context) []*PlatformSecret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformSecretCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformSecretCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
