// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/VMware-AI/agent-platform-backend/ent/predicate"
	"github.com/VMware-AI/agent-platform-backend/ent/providermodel"
	"github.com/google/uuid"
)

// ProviderModelUpdate is the builder for updating ProviderModel entities.
type ProviderModelUpdate struct {
	config
	hooks     []Hook
	mutation  *ProviderModelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProviderModelUpdate builder.
func (_u *ProviderModelUpdate) Where(ps ...predicate.ProviderModel) *ProviderModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderModelUpdate) SetUpdatedAt(v time.Time) *ProviderModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProviderModelUpdate) SetName(v string) *ProviderModelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProviderModelUpdate) SetNillableName(v *string) *ProviderModelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetModelGatewayID sets the "model_gateway_id" field.
func (_u *ProviderModelUpdate) SetModelGatewayID(v uuid.UUID) *ProviderModelUpdate {
	_u.mutation.SetModelGatewayID(v)
	return _u
}

// SetNillableModelGatewayID sets the "model_gateway_id" field if the given value is not nil.
func (_u *ProviderModelUpdate) SetNillableModelGatewayID(v *uuid.UUID) *ProviderModelUpdate {
	if v != nil {
		_u.SetModelGatewayID(*v)
	}
	return _u
}

// SetModelSpecs sets the "model_specs" field.
func (_u *ProviderModelUpdate) SetModelSpecs(v []map[string]interface{}) *ProviderModelUpdate {
	_u.mutation.SetModelSpecs(v)
	return _u
}

// AppendModelSpecs appends value to the "model_specs" field.
func (_u *ProviderModelUpdate) AppendModelSpecs(v []map[string]interface{}) *ProviderModelUpdate {
	_u.mutation.AppendModelSpecs(v)
	return _u
}

// ClearModelSpecs clears the value of the "model_specs" field.
func (_u *ProviderModelUpdate) ClearModelSpecs() *ProviderModelUpdate {
	_u.mutation.ClearModelSpecs()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderModelUpdate) SetStatus(v providermodel.Status) *ProviderModelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderModelUpdate) SetNillableStatus(v *providermodel.Status) *ProviderModelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *ProviderModelUpdate) SetLastCheckedAt(v time.Time) *ProviderModelUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *ProviderModelUpdate) SetNillableLastCheckedAt(v *time.Time) *ProviderModelUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *ProviderModelUpdate) ClearLastCheckedAt() *ProviderModelUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// Mutation returns the ProviderModelMutation object of the builder.
func (_u *ProviderModelUpdate) Mutation() *ProviderModelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providermodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderModelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := providermodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProviderModel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := providermodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderModel.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProviderModelUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProviderModelUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProviderModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providermodel.Table, providermodel.Columns, sqlgraph.NewFieldSpec(providermodel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providermodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(providermodel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelGatewayID(); ok {
		_spec.SetField(providermodel.FieldModelGatewayID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ModelSpecs(); ok {
		_spec.SetField(providermodel.FieldModelSpecs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelSpecs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, providermodel.FieldModelSpecs, value)
		})
	}
	if _u.mutation.ModelSpecsCleared() {
		_spec.ClearField(providermodel.FieldModelSpecs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providermodel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(providermodel.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(providermodel.FieldLastCheckedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providermodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderModelUpdateOne is the builder for updating a single ProviderModel entity.
type ProviderModelUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProviderModelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderModelUpdateOne) SetUpdatedAt(v time.Time) *ProviderModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProviderModelUpdateOne) SetName(v string) *ProviderModelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProviderModelUpdateOne) SetNillableName(v *string) *ProviderModelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetModelGatewayID sets the "model_gateway_id" field.
func (_u *ProviderModelUpdateOne) SetModelGatewayID(v uuid.UUID) *ProviderModelUpdateOne {
	_u.mutation.SetModelGatewayID(v)
	return _u
}

// SetNillableModelGatewayID sets the "model_gateway_id" field if the given value is not nil.
func (_u *ProviderModelUpdateOne) SetNillableModelGatewayID(v *uuid.UUID) *ProviderModelUpdateOne {
	if v != nil {
		_u.SetModelGatewayID(*v)
	}
	return _u
}

// SetModelSpecs sets the "model_specs" field.
func (_u *ProviderModelUpdateOne) SetModelSpecs(v []map[string]interface{}) *ProviderModelUpdateOne {
	_u.mutation.SetModelSpecs(v)
	return _u
}

// AppendModelSpecs appends value to the "model_specs" field.
func (_u *ProviderModelUpdateOne) AppendModelSpecs(v []map[string]interface{}) *ProviderModelUpdateOne {
	_u.mutation.AppendModelSpecs(v)
	return _u
}

// ClearModelSpecs clears the value of the "model_specs" field.
func (_u *ProviderModelUpdateOne) ClearModelSpecs() *ProviderModelUpdateOne {
	_u.mutation.ClearModelSpecs()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderModelUpdateOne) SetStatus(v providermodel.Status) *ProviderModelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderModelUpdateOne) SetNillableStatus(v *providermodel.Status) *ProviderModelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *ProviderModelUpdateOne) SetLastCheckedAt(v time.Time) *ProviderModelUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *ProviderModelUpdateOne) SetNillableLastCheckedAt(v *time.Time) *ProviderModelUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *ProviderModelUpdateOne) ClearLastCheckedAt() *ProviderModelUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// Mutation returns the ProviderModelMutation object of the builder.
func (_u *ProviderModelUpdateOne) Mutation() *ProviderModelMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderModelUpdate builder.
func (_u *ProviderModelUpdateOne) Where(ps ...predicate.ProviderModel) *ProviderModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderModelUpdateOne) Select(field string, fields ...string) *ProviderModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderModel entity.
func (_u *ProviderModelUpdateOne) Save(ctx context.Context) (*ProviderModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderModelUpdateOne) SaveX(ctx context.Context) *ProviderModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providermodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderModelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := providermodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProviderModel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := providermodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderModel.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProviderModelUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProviderModelUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProviderModelUpdateOne) sqlSave(ctx context.Context) (_node *ProviderModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providermodel.Table, providermodel.Columns, sqlgraph.NewFieldSpec(providermodel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providermodel.FieldID)
		for _, f := range fields {
			if !providermodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providermodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providermodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(providermodel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelGatewayID(); ok {
		_spec.SetField(providermodel.FieldModelGatewayID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ModelSpecs(); ok {
		_spec.SetField(providermodel.FieldModelSpecs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelSpecs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, providermodel.FieldModelSpecs, value)
		})
	}
	if _u.mutation.ModelSpecsCleared() {
		_spec.ClearField(providermodel.FieldModelSpecs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providermodel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(providermodel.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(providermodel.FieldLastCheckedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ProviderModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providermodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
