// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/VMware-AI/agent-platform-backend/ent/agent"
	"github.com/VMware-AI/agent-platform-backend/ent/agentconfig"
	"github.com/VMware-AI/agent-platform-backend/ent/agenttemplate"
	"github.com/VMware-AI/agent-platform-backend/ent/artifact"
	"github.com/VMware-AI/agent-platform-backend/ent/auditlog"
	"github.com/VMware-AI/agent-platform-backend/ent/department"
	"github.com/VMware-AI/agent-platform-backend/ent/image"
	"github.com/VMware-AI/agent-platform-backend/ent/membership"
	"github.com/VMware-AI/agent-platform-backend/ent/permission"
	"github.com/VMware-AI/agent-platform-backend/ent/resourcepool"
	"github.com/VMware-AI/agent-platform-backend/ent/role"
	"github.com/VMware-AI/agent-platform-backend/ent/schema"
	"github.com/VMware-AI/agent-platform-backend/ent/skill"
	"github.com/VMware-AI/agent-platform-backend/ent/tenant"
	"github.com/VMware-AI/agent-platform-backend/ent/tokenusage"
	"github.com/VMware-AI/agent-platform-backend/ent/user"
	"github.com/VMware-AI/agent-platform-backend/ent/virtualkey"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentMixin := schema.Agent{}.Mixin()
	agentMixinFields0 := agentMixin[0].Fields()
	_ = agentMixinFields0
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentMixinFields0[0].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	// agentDescUpdatedAt is the schema descriptor for updated_at field.
	agentDescUpdatedAt := agentMixinFields0[1].Descriptor()
	// agent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agent.DefaultUpdatedAt = agentDescUpdatedAt.Default.(func() time.Time)
	// agent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agent.UpdateDefaultUpdatedAt = agentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentDescName is the schema descriptor for name field.
	agentDescName := agentFields[1].Descriptor()
	// agent.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agent.NameValidator = agentDescName.Validators[0].(func(string) error)
	// agentDescAgentType is the schema descriptor for agent_type field.
	agentDescAgentType := agentFields[2].Descriptor()
	// agent.AgentTypeValidator is a validator for the "agent_type" field. It is called by the builders before save.
	agent.AgentTypeValidator = agentDescAgentType.Validators[0].(func(string) error)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentFields[0].Descriptor()
	// agent.DefaultID holds the default value on creation for the id field.
	agent.DefaultID = agentDescID.Default.(func() uuid.UUID)
	agentconfigMixin := schema.AgentConfig{}.Mixin()
	agentconfigMixinFields0 := agentconfigMixin[0].Fields()
	_ = agentconfigMixinFields0
	agentconfigFields := schema.AgentConfig{}.Fields()
	_ = agentconfigFields
	// agentconfigDescCreatedAt is the schema descriptor for created_at field.
	agentconfigDescCreatedAt := agentconfigMixinFields0[0].Descriptor()
	// agentconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentconfig.DefaultCreatedAt = agentconfigDescCreatedAt.Default.(func() time.Time)
	// agentconfigDescUpdatedAt is the schema descriptor for updated_at field.
	agentconfigDescUpdatedAt := agentconfigMixinFields0[1].Descriptor()
	// agentconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentconfig.DefaultUpdatedAt = agentconfigDescUpdatedAt.Default.(func() time.Time)
	// agentconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentconfig.UpdateDefaultUpdatedAt = agentconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentconfigDescName is the schema descriptor for name field.
	agentconfigDescName := agentconfigFields[1].Descriptor()
	// agentconfig.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agentconfig.NameValidator = agentconfigDescName.Validators[0].(func(string) error)
	// agentconfigDescAgentType is the schema descriptor for agent_type field.
	agentconfigDescAgentType := agentconfigFields[2].Descriptor()
	// agentconfig.AgentTypeValidator is a validator for the "agent_type" field. It is called by the builders before save.
	agentconfig.AgentTypeValidator = agentconfigDescAgentType.Validators[0].(func(string) error)
	// agentconfigDescIsDefault is the schema descriptor for is_default field.
	agentconfigDescIsDefault := agentconfigFields[3].Descriptor()
	// agentconfig.DefaultIsDefault holds the default value on creation for the is_default field.
	agentconfig.DefaultIsDefault = agentconfigDescIsDefault.Default.(bool)
	// agentconfigDescID is the schema descriptor for id field.
	agentconfigDescID := agentconfigFields[0].Descriptor()
	// agentconfig.DefaultID holds the default value on creation for the id field.
	agentconfig.DefaultID = agentconfigDescID.Default.(func() uuid.UUID)
	agenttemplateMixin := schema.AgentTemplate{}.Mixin()
	agenttemplateMixinFields0 := agenttemplateMixin[0].Fields()
	_ = agenttemplateMixinFields0
	agenttemplateFields := schema.AgentTemplate{}.Fields()
	_ = agenttemplateFields
	// agenttemplateDescCreatedAt is the schema descriptor for created_at field.
	agenttemplateDescCreatedAt := agenttemplateMixinFields0[0].Descriptor()
	// agenttemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	agenttemplate.DefaultCreatedAt = agenttemplateDescCreatedAt.Default.(func() time.Time)
	// agenttemplateDescUpdatedAt is the schema descriptor for updated_at field.
	agenttemplateDescUpdatedAt := agenttemplateMixinFields0[1].Descriptor()
	// agenttemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agenttemplate.DefaultUpdatedAt = agenttemplateDescUpdatedAt.Default.(func() time.Time)
	// agenttemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agenttemplate.UpdateDefaultUpdatedAt = agenttemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agenttemplateDescKind is the schema descriptor for kind field.
	agenttemplateDescKind := agenttemplateFields[1].Descriptor()
	// agenttemplate.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	agenttemplate.KindValidator = agenttemplateDescKind.Validators[0].(func(string) error)
	// agenttemplateDescDisplay is the schema descriptor for display field.
	agenttemplateDescDisplay := agenttemplateFields[2].Descriptor()
	// agenttemplate.DisplayValidator is a validator for the "display" field. It is called by the builders before save.
	agenttemplate.DisplayValidator = agenttemplateDescDisplay.Validators[0].(func(string) error)
	// agenttemplateDescID is the schema descriptor for id field.
	agenttemplateDescID := agenttemplateFields[0].Descriptor()
	// agenttemplate.DefaultID holds the default value on creation for the id field.
	agenttemplate.DefaultID = agenttemplateDescID.Default.(func() uuid.UUID)
	artifactMixin := schema.Artifact{}.Mixin()
	artifactMixinFields0 := artifactMixin[0].Fields()
	_ = artifactMixinFields0
	artifactFields := schema.Artifact{}.Fields()
	_ = artifactFields
	// artifactDescCreatedAt is the schema descriptor for created_at field.
	artifactDescCreatedAt := artifactMixinFields0[0].Descriptor()
	// artifact.DefaultCreatedAt holds the default value on creation for the created_at field.
	artifact.DefaultCreatedAt = artifactDescCreatedAt.Default.(func() time.Time)
	// artifactDescUpdatedAt is the schema descriptor for updated_at field.
	artifactDescUpdatedAt := artifactMixinFields0[1].Descriptor()
	// artifact.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	artifact.DefaultUpdatedAt = artifactDescUpdatedAt.Default.(func() time.Time)
	// artifact.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	artifact.UpdateDefaultUpdatedAt = artifactDescUpdatedAt.UpdateDefault.(func() time.Time)
	// artifactDescName is the schema descriptor for name field.
	artifactDescName := artifactFields[1].Descriptor()
	// artifact.NameValidator is a validator for the "name" field. It is called by the builders before save.
	artifact.NameValidator = artifactDescName.Validators[0].(func(string) error)
	// artifactDescVersion is the schema descriptor for version field.
	artifactDescVersion := artifactFields[3].Descriptor()
	// artifact.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	artifact.VersionValidator = artifactDescVersion.Validators[0].(func(string) error)
	// artifactDescURI is the schema descriptor for uri field.
	artifactDescURI := artifactFields[4].Descriptor()
	// artifact.URIValidator is a validator for the "uri" field. It is called by the builders before save.
	artifact.URIValidator = artifactDescURI.Validators[0].(func(string) error)
	// artifactDescID is the schema descriptor for id field.
	artifactDescID := artifactFields[0].Descriptor()
	// artifact.DefaultID holds the default value on creation for the id field.
	artifact.DefaultID = artifactDescID.Default.(func() uuid.UUID)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[2].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[8].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	departmentMixin := schema.Department{}.Mixin()
	departmentMixinFields0 := departmentMixin[0].Fields()
	_ = departmentMixinFields0
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescCreatedAt is the schema descriptor for created_at field.
	departmentDescCreatedAt := departmentMixinFields0[0].Descriptor()
	// department.DefaultCreatedAt holds the default value on creation for the created_at field.
	department.DefaultCreatedAt = departmentDescCreatedAt.Default.(func() time.Time)
	// departmentDescUpdatedAt is the schema descriptor for updated_at field.
	departmentDescUpdatedAt := departmentMixinFields0[1].Descriptor()
	// department.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	department.DefaultUpdatedAt = departmentDescUpdatedAt.Default.(func() time.Time)
	// department.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	department.UpdateDefaultUpdatedAt = departmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// departmentDescName is the schema descriptor for name field.
	departmentDescName := departmentFields[2].Descriptor()
	// department.NameValidator is a validator for the "name" field. It is called by the builders before save.
	department.NameValidator = departmentDescName.Validators[0].(func(string) error)
	// departmentDescID is the schema descriptor for id field.
	departmentDescID := departmentFields[0].Descriptor()
	// department.DefaultID holds the default value on creation for the id field.
	department.DefaultID = departmentDescID.Default.(func() uuid.UUID)
	imageMixin := schema.Image{}.Mixin()
	imageMixinFields0 := imageMixin[0].Fields()
	_ = imageMixinFields0
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescCreatedAt is the schema descriptor for created_at field.
	imageDescCreatedAt := imageMixinFields0[0].Descriptor()
	// image.DefaultCreatedAt holds the default value on creation for the created_at field.
	image.DefaultCreatedAt = imageDescCreatedAt.Default.(func() time.Time)
	// imageDescUpdatedAt is the schema descriptor for updated_at field.
	imageDescUpdatedAt := imageMixinFields0[1].Descriptor()
	// image.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	image.DefaultUpdatedAt = imageDescUpdatedAt.Default.(func() time.Time)
	// image.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	image.UpdateDefaultUpdatedAt = imageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// imageDescRepository is the schema descriptor for repository field.
	imageDescRepository := imageFields[1].Descriptor()
	// image.RepositoryValidator is a validator for the "repository" field. It is called by the builders before save.
	image.RepositoryValidator = imageDescRepository.Validators[0].(func(string) error)
	// imageDescTag is the schema descriptor for tag field.
	imageDescTag := imageFields[2].Descriptor()
	// image.TagValidator is a validator for the "tag" field. It is called by the builders before save.
	image.TagValidator = imageDescTag.Validators[0].(func(string) error)
	// imageDescSigned is the schema descriptor for signed field.
	imageDescSigned := imageFields[4].Descriptor()
	// image.DefaultSigned holds the default value on creation for the signed field.
	image.DefaultSigned = imageDescSigned.Default.(bool)
	// imageDescID is the schema descriptor for id field.
	imageDescID := imageFields[0].Descriptor()
	// image.DefaultID holds the default value on creation for the id field.
	image.DefaultID = imageDescID.Default.(func() uuid.UUID)
	membershipMixin := schema.Membership{}.Mixin()
	membershipMixinFields0 := membershipMixin[0].Fields()
	_ = membershipMixinFields0
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescCreatedAt is the schema descriptor for created_at field.
	membershipDescCreatedAt := membershipMixinFields0[0].Descriptor()
	// membership.DefaultCreatedAt holds the default value on creation for the created_at field.
	membership.DefaultCreatedAt = membershipDescCreatedAt.Default.(func() time.Time)
	// membershipDescUpdatedAt is the schema descriptor for updated_at field.
	membershipDescUpdatedAt := membershipMixinFields0[1].Descriptor()
	// membership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membership.DefaultUpdatedAt = membershipDescUpdatedAt.Default.(func() time.Time)
	// membership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membership.UpdateDefaultUpdatedAt = membershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescKey is the schema descriptor for key field.
	permissionDescKey := permissionFields[1].Descriptor()
	// permission.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	permission.KeyValidator = permissionDescKey.Validators[0].(func(string) error)
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionFields[0].Descriptor()
	// permission.DefaultID holds the default value on creation for the id field.
	permission.DefaultID = permissionDescID.Default.(func() uuid.UUID)
	resourcepoolMixin := schema.ResourcePool{}.Mixin()
	resourcepoolMixinFields0 := resourcepoolMixin[0].Fields()
	_ = resourcepoolMixinFields0
	resourcepoolFields := schema.ResourcePool{}.Fields()
	_ = resourcepoolFields
	// resourcepoolDescCreatedAt is the schema descriptor for created_at field.
	resourcepoolDescCreatedAt := resourcepoolMixinFields0[0].Descriptor()
	// resourcepool.DefaultCreatedAt holds the default value on creation for the created_at field.
	resourcepool.DefaultCreatedAt = resourcepoolDescCreatedAt.Default.(func() time.Time)
	// resourcepoolDescUpdatedAt is the schema descriptor for updated_at field.
	resourcepoolDescUpdatedAt := resourcepoolMixinFields0[1].Descriptor()
	// resourcepool.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resourcepool.DefaultUpdatedAt = resourcepoolDescUpdatedAt.Default.(func() time.Time)
	// resourcepool.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resourcepool.UpdateDefaultUpdatedAt = resourcepoolDescUpdatedAt.UpdateDefault.(func() time.Time)
	// resourcepoolDescName is the schema descriptor for name field.
	resourcepoolDescName := resourcepoolFields[1].Descriptor()
	// resourcepool.NameValidator is a validator for the "name" field. It is called by the builders before save.
	resourcepool.NameValidator = resourcepoolDescName.Validators[0].(func(string) error)
	// resourcepoolDescEndpoint is the schema descriptor for endpoint field.
	resourcepoolDescEndpoint := resourcepoolFields[3].Descriptor()
	// resourcepool.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	resourcepool.EndpointValidator = resourcepoolDescEndpoint.Validators[0].(func(string) error)
	// resourcepoolDescID is the schema descriptor for id field.
	resourcepoolDescID := resourcepoolFields[0].Descriptor()
	// resourcepool.DefaultID holds the default value on creation for the id field.
	resourcepool.DefaultID = resourcepoolDescID.Default.(func() uuid.UUID)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescIsSystem is the schema descriptor for is_system field.
	roleDescIsSystem := roleFields[2].Descriptor()
	// role.DefaultIsSystem holds the default value on creation for the is_system field.
	role.DefaultIsSystem = roleDescIsSystem.Default.(bool)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleFields[0].Descriptor()
	// role.DefaultID holds the default value on creation for the id field.
	role.DefaultID = roleDescID.Default.(func() uuid.UUID)
	skillMixin := schema.Skill{}.Mixin()
	skillMixinFields0 := skillMixin[0].Fields()
	_ = skillMixinFields0
	skillFields := schema.Skill{}.Fields()
	_ = skillFields
	// skillDescCreatedAt is the schema descriptor for created_at field.
	skillDescCreatedAt := skillMixinFields0[0].Descriptor()
	// skill.DefaultCreatedAt holds the default value on creation for the created_at field.
	skill.DefaultCreatedAt = skillDescCreatedAt.Default.(func() time.Time)
	// skillDescUpdatedAt is the schema descriptor for updated_at field.
	skillDescUpdatedAt := skillMixinFields0[1].Descriptor()
	// skill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	skill.DefaultUpdatedAt = skillDescUpdatedAt.Default.(func() time.Time)
	// skill.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	skill.UpdateDefaultUpdatedAt = skillDescUpdatedAt.UpdateDefault.(func() time.Time)
	// skillDescName is the schema descriptor for name field.
	skillDescName := skillFields[1].Descriptor()
	// skill.NameValidator is a validator for the "name" field. It is called by the builders before save.
	skill.NameValidator = skillDescName.Validators[0].(func(string) error)
	// skillDescVersion is the schema descriptor for version field.
	skillDescVersion := skillFields[2].Descriptor()
	// skill.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	skill.VersionValidator = skillDescVersion.Validators[0].(func(string) error)
	// skillDescURI is the schema descriptor for uri field.
	skillDescURI := skillFields[4].Descriptor()
	// skill.URIValidator is a validator for the "uri" field. It is called by the builders before save.
	skill.URIValidator = skillDescURI.Validators[0].(func(string) error)
	// skillDescID is the schema descriptor for id field.
	skillDescID := skillFields[0].Descriptor()
	// skill.DefaultID holds the default value on creation for the id field.
	skill.DefaultID = skillDescID.Default.(func() uuid.UUID)
	tenantMixin := schema.Tenant{}.Mixin()
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantMixinFields0[0].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantMixinFields0[1].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	tokenusageFields := schema.TokenUsage{}.Fields()
	_ = tokenusageFields
	// tokenusageDescModel is the schema descriptor for model field.
	tokenusageDescModel := tokenusageFields[3].Descriptor()
	// tokenusage.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	tokenusage.ModelValidator = tokenusageDescModel.Validators[0].(func(string) error)
	// tokenusageDescInputTokens is the schema descriptor for input_tokens field.
	tokenusageDescInputTokens := tokenusageFields[4].Descriptor()
	// tokenusage.DefaultInputTokens holds the default value on creation for the input_tokens field.
	tokenusage.DefaultInputTokens = tokenusageDescInputTokens.Default.(int)
	// tokenusage.InputTokensValidator is a validator for the "input_tokens" field. It is called by the builders before save.
	tokenusage.InputTokensValidator = tokenusageDescInputTokens.Validators[0].(func(int) error)
	// tokenusageDescOutputTokens is the schema descriptor for output_tokens field.
	tokenusageDescOutputTokens := tokenusageFields[5].Descriptor()
	// tokenusage.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	tokenusage.DefaultOutputTokens = tokenusageDescOutputTokens.Default.(int)
	// tokenusage.OutputTokensValidator is a validator for the "output_tokens" field. It is called by the builders before save.
	tokenusage.OutputTokensValidator = tokenusageDescOutputTokens.Validators[0].(func(int) error)
	// tokenusageDescCost is the schema descriptor for cost field.
	tokenusageDescCost := tokenusageFields[6].Descriptor()
	// tokenusage.DefaultCost holds the default value on creation for the cost field.
	tokenusage.DefaultCost = tokenusageDescCost.Default.(float64)
	// tokenusageDescCreatedAt is the schema descriptor for created_at field.
	tokenusageDescCreatedAt := tokenusageFields[10].Descriptor()
	// tokenusage.DefaultCreatedAt holds the default value on creation for the created_at field.
	tokenusage.DefaultCreatedAt = tokenusageDescCreatedAt.Default.(func() time.Time)
	// tokenusageDescID is the schema descriptor for id field.
	tokenusageDescID := tokenusageFields[0].Descriptor()
	// tokenusage.DefaultID holds the default value on creation for the id field.
	tokenusage.DefaultID = tokenusageDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescMustChangePassword is the schema descriptor for must_change_password field.
	userDescMustChangePassword := userFields[6].Descriptor()
	// user.DefaultMustChangePassword holds the default value on creation for the must_change_password field.
	user.DefaultMustChangePassword = userDescMustChangePassword.Default.(bool)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[7].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	virtualkeyMixin := schema.VirtualKey{}.Mixin()
	virtualkeyMixinFields0 := virtualkeyMixin[0].Fields()
	_ = virtualkeyMixinFields0
	virtualkeyFields := schema.VirtualKey{}.Fields()
	_ = virtualkeyFields
	// virtualkeyDescCreatedAt is the schema descriptor for created_at field.
	virtualkeyDescCreatedAt := virtualkeyMixinFields0[0].Descriptor()
	// virtualkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	virtualkey.DefaultCreatedAt = virtualkeyDescCreatedAt.Default.(func() time.Time)
	// virtualkeyDescUpdatedAt is the schema descriptor for updated_at field.
	virtualkeyDescUpdatedAt := virtualkeyMixinFields0[1].Descriptor()
	// virtualkey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	virtualkey.DefaultUpdatedAt = virtualkeyDescUpdatedAt.Default.(func() time.Time)
	// virtualkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	virtualkey.UpdateDefaultUpdatedAt = virtualkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// virtualkeyDescLitellmKey is the schema descriptor for litellm_key field.
	virtualkeyDescLitellmKey := virtualkeyFields[1].Descriptor()
	// virtualkey.LitellmKeyValidator is a validator for the "litellm_key" field. It is called by the builders before save.
	virtualkey.LitellmKeyValidator = virtualkeyDescLitellmKey.Validators[0].(func(string) error)
	// virtualkeyDescID is the schema descriptor for id field.
	virtualkeyDescID := virtualkeyFields[0].Descriptor()
	// virtualkey.DefaultID holds the default value on creation for the id field.
	virtualkey.DefaultID = virtualkeyDescID.Default.(func() uuid.UUID)
}
