// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/VMware-AI/agent-platform-backend/ent/tokenusage"
	"github.com/google/uuid"
)

// TokenUsageCreate is the builder for creating a TokenUsage entity.
type TokenUsageCreate struct {
	config
	mutation *TokenUsageMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *TokenUsageCreate) SetUserID(v uuid.UUID) *TokenUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *TokenUsageCreate) SetAgentID(v uuid.UUID) *TokenUsageCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableAgentID(v *uuid.UUID) *TokenUsageCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *TokenUsageCreate) SetModel(v string) *TokenUsageCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *TokenUsageCreate) SetInputTokens(v int) *TokenUsageCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableInputTokens(v *int) *TokenUsageCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *TokenUsageCreate) SetOutputTokens(v int) *TokenUsageCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableOutputTokens(v *int) *TokenUsageCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *TokenUsageCreate) SetCost(v float64) *TokenUsageCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableCost(v *float64) *TokenUsageCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetCorrelationID sets the "correlation_id" field.
func (_c *TokenUsageCreate) SetCorrelationID(v string) *TokenUsageCreate {
	_c.mutation.SetCorrelationID(v)
	return _c
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableCorrelationID(v *string) *TokenUsageCreate {
	if v != nil {
		_c.SetCorrelationID(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TokenUsageCreate) SetTenantID(v uuid.UUID) *TokenUsageCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableTenantID(v *uuid.UUID) *TokenUsageCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetEnvironmentID sets the "environment_id" field.
func (_c *TokenUsageCreate) SetEnvironmentID(v uuid.UUID) *TokenUsageCreate {
	_c.mutation.SetEnvironmentID(v)
	return _c
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableEnvironmentID(v *uuid.UUID) *TokenUsageCreate {
	if v != nil {
		_c.SetEnvironmentID(*v)
	}
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *TokenUsageCreate) SetDepartmentID(v uuid.UUID) *TokenUsageCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableDepartmentID(v *uuid.UUID) *TokenUsageCreate {
	if v != nil {
		_c.SetDepartmentID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TokenUsageCreate) SetCreatedAt(v time.Time) *TokenUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableCreatedAt(v *time.Time) *TokenUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TokenUsageCreate) SetID(v uuid.UUID) *TokenUsageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TokenUsageCreate) SetNillableID(v *uuid.UUID) *TokenUsageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the TokenUsageMutation object of the builder.
func (_c *TokenUsageCreate) Mutation() *TokenUsageMutation {
	return _c.mutation
}

// Save creates the TokenUsage in the database.
func (_c *TokenUsageCreate) Save(ctx context.Context) (*TokenUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TokenUsageCreate) SaveX(ctx context.Context) *TokenUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TokenUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TokenUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TokenUsageCreate) defaults() {
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := tokenusage.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := tokenusage.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := tokenusage.DefaultCost
		_c.mutation.SetCost(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tokenusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tokenusage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TokenUsageCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TokenUsage.user_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "TokenUsage.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := tokenusage.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "TokenUsage.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "TokenUsage.input_tokens"`)}
	}
	if v, ok := _c.mutation.InputTokens(); ok {
		if err := tokenusage.InputTokensValidator(v); err != nil {
			return &ValidationError{Name: "input_tokens", err: fmt.Errorf(`ent: validator failed for field "TokenUsage.input_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "TokenUsage.output_tokens"`)}
	}
	if v, ok := _c.mutation.OutputTokens(); ok {
		if err := tokenusage.OutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "output_tokens", err: fmt.Errorf(`ent: validator failed for field "TokenUsage.output_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TokenUsage.created_at"`)}
	}
	return nil
}

func (_c *TokenUsageCreate) sqlSave(ctx context.Context) (*TokenUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TokenUsageCreate) createSpec() (*TokenUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &TokenUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tokenusage.Table, sqlgraph.NewFieldSpec(tokenusage.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(tokenusage.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(tokenusage.FieldAgentID, field.TypeUUID, value)
		_node.AgentID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(tokenusage.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(tokenusage.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(tokenusage.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(tokenusage.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.CorrelationID(); ok {
		_spec.SetField(tokenusage.FieldCorrelationID, field.TypeString, value)
		_node.CorrelationID = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tokenusage.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.EnvironmentID(); ok {
		_spec.SetField(tokenusage.FieldEnvironmentID, field.TypeUUID, value)
		_node.EnvironmentID = &value
	}
	if value, ok := _c.mutation.DepartmentID(); ok {
		_spec.SetField(tokenusage.FieldDepartmentID, field.TypeUUID, value)
		_node.DepartmentID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tokenusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TokenUsageCreateBulk is the builder for creating many TokenUsage entities in bulk.
type TokenUsageCreateBulk struct {
	config
	err      error
	builders []*TokenUsageCreate
}

// Save creates the TokenUsage entities in the database.
func (_c *TokenUsageCreateBulk) Save(ctx context.Context) ([]*TokenUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TokenUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TokenUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TokenUsageCreateBulk) SaveX(ctx context.Context) []*TokenUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TokenUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TokenUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
