// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/VMware-AI/agent-platform-backend/ent/agent"
	"github.com/VMware-AI/agent-platform-backend/ent/predicate"
	"github.com/VMware-AI/agent-platform-backend/ent/virtualkey"
	"github.com/google/uuid"
)

// VirtualKeyQuery is the builder for querying VirtualKey entities.
type VirtualKeyQuery struct {
	config
	ctx        *QueryContext
	order      []virtualkey.OrderOption
	inters     []Interceptor
	predicates []predicate.VirtualKey
	withAgent  *AgentQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VirtualKeyQuery builder.
func (_q *VirtualKeyQuery) Where(ps ...predicate.VirtualKey) *VirtualKeyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VirtualKeyQuery) Limit(limit int) *VirtualKeyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VirtualKeyQuery) Offset(offset int) *VirtualKeyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VirtualKeyQuery) Unique(unique bool) *VirtualKeyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VirtualKeyQuery) Order(o ...virtualkey.OrderOption) *VirtualKeyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAgent chains the current query on the "agent" edge.
func (_q *VirtualKeyQuery) QueryAgent() *AgentQuery {
	query := (&AgentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(virtualkey.Table, virtualkey.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, virtualkey.AgentTable, virtualkey.AgentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VirtualKey entity from the query.
// Returns a *NotFoundError when no VirtualKey was found.
func (_q *VirtualKeyQuery) First(ctx context.Context) (*VirtualKey, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{virtualkey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VirtualKeyQuery) FirstX(ctx context.Context) *VirtualKey {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VirtualKey ID from the query.
// Returns a *NotFoundError when no VirtualKey ID was found.
func (_q *VirtualKeyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{virtualkey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VirtualKeyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VirtualKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VirtualKey entity is found.
// Returns a *NotFoundError when no VirtualKey entities are found.
func (_q *VirtualKeyQuery) Only(ctx context.Context) (*VirtualKey, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{virtualkey.Label}
	default:
		return nil, &NotSingularError{virtualkey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VirtualKeyQuery) OnlyX(ctx context.Context) *VirtualKey {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VirtualKey ID in the query.
// Returns a *NotSingularError when more than one VirtualKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VirtualKeyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{virtualkey.Label}
	default:
		err = &NotSingularError{virtualkey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VirtualKeyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VirtualKeys.
func (_q *VirtualKeyQuery) All(ctx context.Context) ([]*VirtualKey, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VirtualKey, *VirtualKeyQuery]()
	return withInterceptors[[]*VirtualKey](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VirtualKeyQuery) AllX(ctx context.Context) []*VirtualKey {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VirtualKey IDs.
func (_q *VirtualKeyQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(virtualkey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VirtualKeyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VirtualKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VirtualKeyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VirtualKeyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VirtualKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VirtualKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VirtualKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VirtualKeyQuery) Clone() *VirtualKeyQuery {
	if _q == nil {
		return nil
	}
	return &VirtualKeyQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]virtualkey.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.VirtualKey{}, _q.predicates...),
		withAgent:  _q.withAgent.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAgent tells the query-builder to eager-load the nodes that are connected to
// the "agent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VirtualKeyQuery) WithAgent(opts ...func(*AgentQuery)) *VirtualKeyQuery {
	query := (&AgentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgent = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VirtualKey.Query().
//		GroupBy(virtualkey.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VirtualKeyQuery) GroupBy(field string, fields ...string) *VirtualKeyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VirtualKeyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = virtualkey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.VirtualKey.Query().
//		Select(virtualkey.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *VirtualKeyQuery) Select(fields ...string) *VirtualKeySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VirtualKeySelect{VirtualKeyQuery: _q}
	sbuild.label = virtualkey.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VirtualKeySelect configured with the given aggregations.
func (_q *VirtualKeyQuery) Aggregate(fns ...AggregateFunc) *VirtualKeySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VirtualKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !virtualkey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VirtualKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VirtualKey, error) {
	var (
		nodes       = []*VirtualKey{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withAgent != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VirtualKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VirtualKey{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAgent; query != nil {
		if err := _q.loadAgent(ctx, query, nodes, nil,
			func(n *VirtualKey, e *Agent) { n.Edges.Agent = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VirtualKeyQuery) loadAgent(ctx context.Context, query *AgentQuery, nodes []*VirtualKey, init func(*VirtualKey), assign func(*VirtualKey, *Agent)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*VirtualKey)
	for i := range nodes {
		if nodes[i].AgentID == nil {
			continue
		}
		fk := *nodes[i].AgentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *VirtualKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VirtualKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(virtualkey.Table, virtualkey.Columns, sqlgraph.NewFieldSpec(virtualkey.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, virtualkey.FieldID)
		for i := range fields {
			if fields[i] != virtualkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAgent != nil {
			_spec.Node.AddColumnOnce(virtualkey.FieldAgentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VirtualKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(virtualkey.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = virtualkey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *VirtualKeyQuery) Modify(modifiers ...func(s *sql.Selector)) *VirtualKeySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// VirtualKeyGroupBy is the group-by builder for VirtualKey entities.
type VirtualKeyGroupBy struct {
	selector
	build *VirtualKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VirtualKeyGroupBy) Aggregate(fns ...AggregateFunc) *VirtualKeyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VirtualKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VirtualKeyQuery, *VirtualKeyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VirtualKeyGroupBy) sqlScan(ctx context.Context, root *VirtualKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VirtualKeySelect is the builder for selecting fields of VirtualKey entities.
type VirtualKeySelect struct {
	*VirtualKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VirtualKeySelect) Aggregate(fns ...AggregateFunc) *VirtualKeySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VirtualKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VirtualKeyQuery, *VirtualKeySelect](ctx, _s.VirtualKeyQuery, _s, _s.inters, v)
}

func (_s *VirtualKeySelect) sqlScan(ctx context.Context, root *VirtualKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *VirtualKeySelect) Modify(modifiers ...func(s *sql.Selector)) *VirtualKeySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
