// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/VMware-AI/agent-platform-backend/ent/virtualkey"
	"github.com/google/uuid"
)

// VirtualKeyCreate is the builder for creating a VirtualKey entity.
type VirtualKeyCreate struct {
	config
	mutation *VirtualKeyMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *VirtualKeyCreate) SetCreatedAt(v time.Time) *VirtualKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VirtualKeyCreate) SetNillableCreatedAt(v *time.Time) *VirtualKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VirtualKeyCreate) SetUpdatedAt(v time.Time) *VirtualKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VirtualKeyCreate) SetNillableUpdatedAt(v *time.Time) *VirtualKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLitellmKey sets the "litellm_key" field.
func (_c *VirtualKeyCreate) SetLitellmKey(v string) *VirtualKeyCreate {
	_c.mutation.SetLitellmKey(v)
	return _c
}

// SetAlias sets the "alias" field.
func (_c *VirtualKeyCreate) SetAlias(v string) *VirtualKeyCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_c *VirtualKeyCreate) SetNillableAlias(v *string) *VirtualKeyCreate {
	if v != nil {
		_c.SetAlias(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VirtualKeyCreate) SetUserID(v uuid.UUID) *VirtualKeyCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *VirtualKeyCreate) SetTeamID(v string) *VirtualKeyCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_c *VirtualKeyCreate) SetNillableTeamID(v *string) *VirtualKeyCreate {
	if v != nil {
		_c.SetTeamID(*v)
	}
	return _c
}

// SetModels sets the "models" field.
func (_c *VirtualKeyCreate) SetModels(v []string) *VirtualKeyCreate {
	_c.mutation.SetModels(v)
	return _c
}

// SetMaxBudget sets the "max_budget" field.
func (_c *VirtualKeyCreate) SetMaxBudget(v float64) *VirtualKeyCreate {
	_c.mutation.SetMaxBudget(v)
	return _c
}

// SetNillableMaxBudget sets the "max_budget" field if the given value is not nil.
func (_c *VirtualKeyCreate) SetNillableMaxBudget(v *float64) *VirtualKeyCreate {
	if v != nil {
		_c.SetMaxBudget(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *VirtualKeyCreate) SetStatus(v virtualkey.Status) *VirtualKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VirtualKeyCreate) SetNillableStatus(v *virtualkey.Status) *VirtualKeyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *VirtualKeyCreate) SetExpiresAt(v time.Time) *VirtualKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *VirtualKeyCreate) SetNillableExpiresAt(v *time.Time) *VirtualKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VirtualKeyCreate) SetID(v uuid.UUID) *VirtualKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VirtualKeyCreate) SetNillableID(v *uuid.UUID) *VirtualKeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the VirtualKeyMutation object of the builder.
func (_c *VirtualKeyCreate) Mutation() *VirtualKeyMutation {
	return _c.mutation
}

// Save creates the VirtualKey in the database.
func (_c *VirtualKeyCreate) Save(ctx context.Context) (*VirtualKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VirtualKeyCreate) SaveX(ctx context.Context) *VirtualKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VirtualKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VirtualKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VirtualKeyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := virtualkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := virtualkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := virtualkey.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := virtualkey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VirtualKeyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VirtualKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VirtualKey.updated_at"`)}
	}
	if _, ok := _c.mutation.LitellmKey(); !ok {
		return &ValidationError{Name: "litellm_key", err: errors.New(`ent: missing required field "VirtualKey.litellm_key"`)}
	}
	if v, ok := _c.mutation.LitellmKey(); ok {
		if err := virtualkey.LitellmKeyValidator(v); err != nil {
			return &ValidationError{Name: "litellm_key", err: fmt.Errorf(`ent: validator failed for field "VirtualKey.litellm_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VirtualKey.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VirtualKey.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := virtualkey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VirtualKey.status": %w`, err)}
		}
	}
	return nil
}

func (_c *VirtualKeyCreate) sqlSave(ctx context.Context) (*VirtualKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VirtualKeyCreate) createSpec() (*VirtualKey, *sqlgraph.CreateSpec) {
	var (
		_node = &VirtualKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(virtualkey.Table, sqlgraph.NewFieldSpec(virtualkey.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(virtualkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(virtualkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LitellmKey(); ok {
		_spec.SetField(virtualkey.FieldLitellmKey, field.TypeString, value)
		_node.LitellmKey = value
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(virtualkey.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(virtualkey.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.TeamID(); ok {
		_spec.SetField(virtualkey.FieldTeamID, field.TypeString, value)
		_node.TeamID = value
	}
	if value, ok := _c.mutation.Models(); ok {
		_spec.SetField(virtualkey.FieldModels, field.TypeJSON, value)
		_node.Models = value
	}
	if value, ok := _c.mutation.MaxBudget(); ok {
		_spec.SetField(virtualkey.FieldMaxBudget, field.TypeFloat64, value)
		_node.MaxBudget = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(virtualkey.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(virtualkey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// VirtualKeyCreateBulk is the builder for creating many VirtualKey entities in bulk.
type VirtualKeyCreateBulk struct {
	config
	err      error
	builders []*VirtualKeyCreate
}

// Save creates the VirtualKey entities in the database.
func (_c *VirtualKeyCreateBulk) Save(ctx context.Context) ([]*VirtualKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VirtualKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VirtualKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VirtualKeyCreateBulk) SaveX(ctx context.Context) []*VirtualKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VirtualKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VirtualKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
