// Code generated by ent, DO NOT EDIT.

package ovatemplateversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ovatemplateversion type in the database.
	Label = "ova_template_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldOvaIdentifier holds the string denoting the ova_identifier field in the database.
	FieldOvaIdentifier = "ova_identifier"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldFamilyID holds the string denoting the family_id field in the database.
	FieldFamilyID = "family_id"
	// EdgeFamily holds the string denoting the family edge name in mutations.
	EdgeFamily = "family"
	// Table holds the table name of the ovatemplateversion in the database.
	Table = "ova_template_versions"
	// FamilyTable is the table that holds the family relation/edge.
	FamilyTable = "ova_template_versions"
	// FamilyInverseTable is the table name for the OvaTemplateFamily entity.
	// It exists in this package in order to avoid circular dependency with the "ovatemplatefamily" package.
	FamilyInverseTable = "ova_template_families"
	// FamilyColumn is the table column denoting the family relation/edge.
	FamilyColumn = "family_id"
)

// Columns holds all SQL columns for ovatemplateversion fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldVersion,
	FieldOvaIdentifier,
	FieldNotes,
	FieldFamilyID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// OvaIdentifierValidator is a validator for the "ova_identifier" field. It is called by the builders before save.
	OvaIdentifierValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the OvaTemplateVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByOvaIdentifier orders the results by the ova_identifier field.
func ByOvaIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOvaIdentifier, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByFamilyID orders the results by the family_id field.
func ByFamilyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFamilyID, opts...).ToFunc()
}

// ByFamilyField orders the results by family field.
func ByFamilyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFamilyStep(), sql.OrderByField(field, opts...))
	}
}
func newFamilyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FamilyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FamilyTable, FamilyColumn),
	)
}
