-- Modify "gateway_connections" table
ALTER TABLE "gateway_connections" ALTER COLUMN "load_balance_strategy" SET DEFAULT 'SIMPLE_SHUFFLE', ALTER COLUMN "backend_model_count" TYPE bigint;
-- Modify "model_routes" table
ALTER TABLE "model_routes" ALTER COLUMN "strategy" SET DEFAULT 'SIMPLE_SHUFFLE';
-- Create "platform_secrets" table
CREATE TABLE "platform_secrets" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "ref" character varying NOT NULL, "username" character varying NULL DEFAULT '', "password" character varying NULL DEFAULT '', "api_key" character varying NULL DEFAULT '', PRIMARY KEY ("id"));
-- Create index "platform_secrets_ref_key" to table: "platform_secrets"
CREATE UNIQUE INDEX "platform_secrets_ref_key" ON "platform_secrets" ("ref");
-- Create index "platformsecret_ref" to table: "platform_secrets"
CREATE INDEX "platformsecret_ref" ON "platform_secrets" ("ref");
