package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"crypto/sha256"
	"encoding/hex"

	"github.com/VMware-AI/agent-platform-backend/ent"
	"github.com/VMware-AI/agent-platform-backend/ent/artifact"
	"github.com/VMware-AI/agent-platform-backend/ent/image"
	"github.com/VMware-AI/agent-platform-backend/ent/skill"
	"github.com/VMware-AI/agent-platform-backend/internal/auth"
	"github.com/VMware-AI/agent-platform-backend/internal/graph/model"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// UpsertArtifact is the resolver for the upsertArtifact field.
func (r *mutationResolver) UpsertArtifact(ctx context.Context, input model.UpsertArtifactInput) (*model.Artifact, error) {
	// Inline content is for small text artifacts only (config/script); packages
	// reference a uri. When present we recompute sha256 from the bytes so the
	// stored digest always matches the stored content (LLD-09).
	var content, contentSHA string
	if input.Content != nil && *input.Content != "" {
		if input.Kind == model.ArtifactKindPackage {
			return nil, gqlerror.Errorf("inline content is not allowed for package artifacts; use uri")
		}
		if len(*input.Content) > maxArtifactContent {
			return nil, gqlerror.Errorf("inline content exceeds %d-byte limit", maxArtifactContent)
		}
		content = *input.Content
		sum := sha256.Sum256([]byte(content))
		contentSHA = hex.EncodeToString(sum[:])
	}

	tenantID, err := writeTenant(ctx)
	if err != nil {
		return nil, err
	}
	// Look up within the SAME tenant scope as the write (LLD-10 §1.7): names are
	// unique per tenant, so the find-or-create must match the caller's tenant
	// (admin/platform → the NULL-tenant namespace).
	lookup := r.Ent.Artifact.Query().Where(artifact.Name(input.Name), artifact.Version(input.Version))
	if tenantID != nil {
		lookup = lookup.Where(artifact.TenantID(*tenantID))
	} else {
		lookup = lookup.Where(artifact.TenantIDIsNil())
	}
	existing, err := lookup.Only(ctx)
	var a *ent.Artifact
	switch {
	case ent.IsNotFound(err):
		c := r.Ent.Artifact.Create().
			SetName(input.Name).SetKind(artifact.Kind(input.Kind)).
			SetVersion(input.Version).SetURI(input.URI).
			SetNillableTenantID(tenantID)
		if content != "" {
			c.SetContent(content).SetSha256(contentSHA)
		} else if input.Sha256 != nil {
			c.SetSha256(*input.Sha256)
		}
		if input.Metadata != nil {
			c.SetMetadata(input.Metadata)
		}
		a, err = c.Save(ctx)
	case err != nil:
		return nil, err
	default:
		u := existing.Update().SetKind(artifact.Kind(input.Kind)).SetURI(input.URI)
		if content != "" {
			u.SetContent(content).SetSha256(contentSHA)
		} else if input.Sha256 != nil {
			u.SetSha256(*input.Sha256)
		}
		if input.Metadata != nil {
			u.SetMetadata(input.Metadata)
		}
		a, err = u.Save(ctx)
	}
	if err != nil {
		return nil, err
	}
	r.audit(ctx, "artifact.upsert", "artifact", a.ID.String(), true, actorID(auth.FromContext(ctx)))
	return toModelArtifact(a), nil
}

// DeleteArtifact is the resolver for the deleteArtifact field.
func (r *mutationResolver) DeleteArtifact(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, gqlerror.Errorf("invalid id")
	}
	// Tenant 404 oracle (LLD-10 §1.5): a tenant-scoped caller may only delete
	// their own tenant's artifact; a cross-tenant / platform row reads as missing.
	art, err := r.Ent.Artifact.Get(ctx, uid)
	if err != nil {
		if ent.IsNotFound(err) {
			return false, notFoundErr("artifact")
		}
		return false, err
	}
	if !writeAllowed(ctx, art.TenantID) {
		return false, notFoundErr("artifact")
	}
	if err := r.Ent.Artifact.DeleteOneID(uid).Exec(ctx); err != nil {
		return false, err
	}
	r.audit(ctx, "artifact.delete", "artifact", id, true, actorID(auth.FromContext(ctx)))
	return true, nil
}

// UpsertSkill is the resolver for the upsertSkill field.
func (r *mutationResolver) UpsertSkill(ctx context.Context, input model.UpsertSkillInput) (*model.Skill, error) {
	existing, err := r.Ent.Skill.Query().
		Where(skill.Name(input.Name), skill.Version(input.Version)).Only(ctx)
	var s *ent.Skill
	switch {
	case ent.IsNotFound(err):
		c := r.Ent.Skill.Create().SetName(input.Name).SetVersion(input.Version).SetURI(input.URI)
		if input.Description != nil {
			c.SetDescription(*input.Description)
		}
		s, err = c.Save(ctx)
	case err != nil:
		return nil, err
	default:
		u := existing.Update().SetURI(input.URI)
		if input.Description != nil {
			u.SetDescription(*input.Description)
		}
		s, err = u.Save(ctx)
	}
	if err != nil {
		return nil, err
	}
	r.audit(ctx, "skill.upsert", "skill", s.ID.String(), true, actorID(auth.FromContext(ctx)))
	return toModelSkill(s), nil
}

// DeleteSkill is the resolver for the deleteSkill field.
func (r *mutationResolver) DeleteSkill(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, gqlerror.Errorf("invalid id")
	}
	if err := r.Ent.Skill.DeleteOneID(uid).Exec(ctx); err != nil {
		return false, err
	}
	r.audit(ctx, "skill.delete", "skill", id, true, actorID(auth.FromContext(ctx)))
	return true, nil
}

// UpsertImage is the resolver for the upsertImage field.
func (r *mutationResolver) UpsertImage(ctx context.Context, input model.UpsertImageInput) (*model.Image, error) {
	signed := false
	if input.Signed != nil {
		signed = *input.Signed
	}
	existing, err := r.Ent.Image.Query().
		Where(image.Repository(input.Repository), image.Tag(input.Tag)).Only(ctx)
	var img *ent.Image
	switch {
	case ent.IsNotFound(err):
		c := r.Ent.Image.Create().SetRepository(input.Repository).SetTag(input.Tag).SetSigned(signed)
		if input.Digest != nil {
			c.SetDigest(*input.Digest)
		}
		img, err = c.Save(ctx)
	case err != nil:
		return nil, err
	default:
		u := existing.Update().SetSigned(signed)
		if input.Digest != nil {
			u.SetDigest(*input.Digest)
		}
		img, err = u.Save(ctx)
	}
	if err != nil {
		return nil, err
	}
	r.audit(ctx, "image.upsert", "image", img.ID.String(), true, actorID(auth.FromContext(ctx)))
	return toModelImage(img), nil
}

// DeleteImage is the resolver for the deleteImage field.
func (r *mutationResolver) DeleteImage(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, gqlerror.Errorf("invalid id")
	}
	if err := r.Ent.Image.DeleteOneID(uid).Exec(ctx); err != nil {
		return false, err
	}
	r.audit(ctx, "image.delete", "image", id, true, actorID(auth.FromContext(ctx)))
	return true, nil
}

// Artifacts is the resolver for the artifacts field.
func (r *queryResolver) Artifacts(ctx context.Context, kind *model.ArtifactKind) ([]model.Artifact, error) {
	q := r.Ent.Artifact.Query()
	if kind != nil {
		q = q.Where(artifact.KindEQ(artifact.Kind(string(*kind)))) // e.g. knowledge picker (LLD-11 K2)
	}
	// Tenant isolation (LLD-10 §9): a caller with a tenant sees their tenant's +
	// platform-global (NULL) artifacts; admin sees all; malformed tenant → none.
	if d := contentScopeFor(ctx); d.apply {
		if d.denyAll {
			q = q.Where(artifact.IDEQ(uuid.Nil))
		} else {
			q = q.Where(artifact.Or(artifact.TenantID(d.tenant), artifact.TenantIDIsNil()))
		}
	}
	if env, ok := r.envScopeFor(ctx); ok {
		q = q.Where(artifact.Or(artifact.EnvironmentID(env), artifact.EnvironmentIDIsNil()))
	}
	as, err := q.Order(orderNewest).All(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Artifact, 0, len(as))
	for _, a := range as {
		out = append(out, *toModelArtifact(a))
	}
	return out, nil
}

// ArtifactVersions lists every version of a named artifact, newest first (制品库
// 版本列表, LLD-06 §3).
func (r *queryResolver) ArtifactVersions(ctx context.Context, name string) ([]model.Artifact, error) {
	q := r.Ent.Artifact.Query().Where(artifact.Name(name))
	if d := contentScopeFor(ctx); d.apply {
		if d.denyAll {
			q = q.Where(artifact.IDEQ(uuid.Nil))
		} else {
			q = q.Where(artifact.Or(artifact.TenantID(d.tenant), artifact.TenantIDIsNil()))
		}
	}
	if env, ok := r.envScopeFor(ctx); ok {
		q = q.Where(artifact.Or(artifact.EnvironmentID(env), artifact.EnvironmentIDIsNil()))
	}
	as, err := q.Order(orderNewest).All(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Artifact, 0, len(as))
	for _, a := range as {
		out = append(out, *toModelArtifact(a))
	}
	return out, nil
}

// Skills is the resolver for the skills field.
func (r *queryResolver) Skills(ctx context.Context) ([]model.Skill, error) {
	ss, err := r.Ent.Skill.Query().Order(orderNewest).All(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Skill, 0, len(ss))
	for _, s := range ss {
		out = append(out, *toModelSkill(s))
	}
	return out, nil
}

// Images is the resolver for the images field.
func (r *queryResolver) Images(ctx context.Context) ([]model.Image, error) {
	is, err := r.Ent.Image.Query().Order(orderNewest).All(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Image, 0, len(is))
	for _, i := range is {
		out = append(out, *toModelImage(i))
	}
	return out, nil
}
