package graph

import "testing"

// authExemptFields are the Query/Mutation fields that intentionally carry NO
// @hasRole/@hasPermission directive. Two reasons only:
//
//   - public / self-scoped: reachable pre-auth or scoped to the caller themselves;
//   - resolver-authz: authorization is enforced inside the resolver (owner-track
//     via getOwnedAgent, department delegation via canManageDepartment, an inline
//     admin check, or — pending LLD-10 B2 — tenant scoping).
//
// This list is the fail-closed contract (LLD-10 §3.1): any NEW Query/Mutation
// field must either declare a directive or be added here deliberately (which
// forces a reviewer to confirm where its authz lives). A field that is neither
// fails TestDirectiveCoverage.
var authExemptFields = map[string]string{
	// public / self
	"login":          "public (pre-auth)",
	"logout":         "self",
	"me":             "self",
	"changePassword": "self",
	// resolver-authz: owner track / inline admin / catalog
	"agents":                "owner track (Agents filters by owner; tenant-admin branch pending B2)",
	"createAgent":           "owner = caller",
	"setAgentStatus":        "owner oracle (getOwnedAgent)",
	"agentTemplates":        "public catalog read",
	"deployAgent":           "owner/admin in resolver (getOwnedAgent)",
	"recycleAgent":          "owner/admin in resolver",
	"vmTemplates":           "inline admin-only check",
	"agentSnapshots":        "owner/admin in resolver",
	"snapshotAgent":         "owner/admin in resolver",
	"revertAgentSnapshot":   "owner/admin in resolver",
	"requestRotation":       "owner/admin in resolver",
	"revokeAgentEnrollment": "owner/admin in resolver",
	// department delegation (canManageDepartment, includes tenant check)
	"departmentMembers": "canManageDepartment",
	"addMembership":     "canManageDepartment",
	"removeMembership":  "canManageDepartment",
	// content/catalog — any authenticated user, tenant-scoped IN-RESOLVER via
	// contentScopeFor (not a directive), hence exempt here (LLD-10 B2 done).
	"agentConfigs":     "content: contentScopeFor (tenant+platform)",
	"artifacts":        "content: contentScopeFor (tenant+platform)",
	"artifactVersions": "content: contentScopeFor (tenant+platform)",
	// Skill/Image are C-class platform-global (no tenant_id) — global read.
	"skills": "C-class global catalog",
	"images": "C-class global catalog",
}

// fieldGuarded is the single source of truth for the fail-closed contract: a
// root field is OK iff it carries an authz directive OR is an explicit exemption.
func fieldGuarded(f fieldInfo) bool {
	for _, d := range f.directives {
		if d == "hasRole" || d == "hasPermission" {
			return true
		}
	}
	_, ok := authExemptFields[f.name]
	return ok
}

// TestDirectiveCoverage asserts every root Query/Mutation field is either gated
// by an authz directive or explicitly exempted above (LLD-10 §3.1 fail-closed).
func TestDirectiveCoverage(t *testing.T) {
	for _, typeName := range []string{"Query", "Mutation"} {
		for _, f := range rootFields(typeName) {
			if !fieldGuarded(f) {
				t.Errorf("%s.%s has no @hasRole/@hasPermission and is not in authExemptFields "+
					"(fail-closed: add a directive or exempt it deliberately)", typeName, f.name)
			}
		}
	}
}

// TestDirectiveCoverage_DetectsGap proves the guard CATCHES a violation (AC-10):
// a fabricated mutation with neither directive nor exemption must be flagged,
// while a directive-bearing one passes.
func TestDirectiveCoverage_DetectsGap(t *testing.T) {
	if fieldGuarded(fieldInfo{name: "brandNewUnguardedMutation"}) {
		t.Fatal("an unguarded, unexempted field must NOT be considered guarded")
	}
	if !fieldGuarded(fieldInfo{name: "x", directives: []string{"hasRole"}}) {
		t.Fatal("a directive-bearing field must be considered guarded")
	}
}

type fieldInfo struct {
	name       string
	directives []string
}
type fieldList []fieldInfo

// rootFields reads the compiled schema (parsedSchema, generated by gqlgen) for a
// root type's fields and their directive names.
func rootFields(typeName string) fieldList {
	def := parsedSchema.Types[typeName]
	if def == nil {
		return nil
	}
	out := make(fieldList, 0, len(def.Fields))
	for _, f := range def.Fields {
		// skip introspection meta-fields
		if len(f.Name) > 1 && f.Name[0] == '_' && f.Name[1] == '_' {
			continue
		}
		names := make([]string, 0, len(f.Directives))
		for _, d := range f.Directives {
			names = append(names, d.Name)
		}
		out = append(out, fieldInfo{name: f.Name, directives: names})
	}
	return out
}
