package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/VMware-AI/agent-platform-backend/internal/graph/model"
)

// SpendReport is the resolver for the spendReport field.
func (r *queryResolver) SpendReport(ctx context.Context, input model.SpendReportInput) (*model.SpendReport, error) {
	return r.Resolver.spendReport(ctx, input)
}

// Budgets is the resolver for the budgets field.
func (r *queryResolver) Budgets(ctx context.Context, scope model.BudgetScope) ([]model.Budget, error) {
	return r.Resolver.budgets(ctx, scope)
}
