package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"time"

	"github.com/VMware-AI/agent-platform-backend/ent/agent"
	"github.com/VMware-AI/agent-platform-backend/ent/requestlog"
	"github.com/VMware-AI/agent-platform-backend/internal/graph/model"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// RecordRequestLog ingests a gateway request-log record.
func (r *mutationResolver) RecordRequestLog(ctx context.Context, input model.RecordRequestLogInput) (*model.RequestLog, error) {
	c := r.Ent.RequestLog.Create().
		SetRequestID(input.RequestID).
		SetInputTokens(intOrZero(input.InputTokens)).
		SetOutputTokens(intOrZero(input.OutputTokens)).
		SetLatencyMs(intOrZero(input.LatencyMs)).
		SetStatusCode(input.StatusCode)
	if input.Model != nil {
		c.SetModel(*input.Model)
	}
	if input.UserID != nil {
		if uid, err := uuid.Parse(*input.UserID); err == nil {
			c.SetUserID(uid)
		}
	}
	if input.AgentID != nil {
		if aid, err := uuid.Parse(*input.AgentID); err == nil {
			c.SetAgentID(aid)
		}
	}
	if input.Detail != nil {
		c.SetDetail(*input.Detail)
	}
	l, err := c.Save(ctx)
	if err != nil {
		return nil, err
	}
	return toModelRequestLog(l), nil
}

// RequestLogs lists gateway request logs with optional filters (0619 第11页).
func (r *queryResolver) RequestLogs(ctx context.Context, filter *model.RequestLogFilter, page *model.PageInput) (*model.RequestLogConnection, error) {
	q := r.Ent.RequestLog.Query()
	if filter != nil {
		if filter.StatusCode != nil {
			q = q.Where(requestlog.StatusCode(*filter.StatusCode))
		}
		if filter.Model != nil {
			q = q.Where(requestlog.Model(*filter.Model))
		}
		if filter.RequestID != nil {
			q = q.Where(requestlog.RequestID(*filter.RequestID))
		}
		if filter.AgentID != nil {
			// Fail closed: a malformed UUID must not silently drop the predicate
			// and return every tenant's logs unfiltered (mirrors MeteringRecords).
			aid, err := uuid.Parse(*filter.AgentID)
			if err != nil {
				return nil, gqlerror.Errorf("invalid agentId")
			}
			q = q.Where(requestlog.AgentID(aid))
		}
		if filter.UserID != nil {
			uid, err := uuid.Parse(*filter.UserID)
			if err != nil {
				return nil, gqlerror.Errorf("invalid userId")
			}
			q = q.Where(requestlog.UserID(uid))
		}
		if filter.From != nil {
			q = q.Where(requestlog.CreatedAtGTE(*filter.From))
		}
		if filter.To != nil {
			q = q.Where(requestlog.CreatedAtLTE(*filter.To))
		}
		if filter.StatusClass != nil {
			// Translate the band to a code range; keeps the raw range server-side.
			switch *filter.StatusClass {
			case model.RequestStatusClassSuccess:
				q = q.Where(requestlog.StatusCodeGTE(200), requestlog.StatusCodeLT(300))
			case model.RequestStatusClassClientError:
				q = q.Where(requestlog.StatusCodeGTE(400), requestlog.StatusCodeLT(500))
			case model.RequestStatusClassServerError:
				q = q.Where(requestlog.StatusCodeGTE(500), requestlog.StatusCodeLT(600))
			}
		}
	}
	// Tenant isolation (LLD-10 B-class): a request log belongs to its user's /
	// agent's tenant; a tenant-admin sees only their tenant's traffic.
	if d := tenantScopeFor(ctx); d.apply {
		if d.denyAll {
			q = q.Where(requestlog.IDEQ(uuid.Nil))
		} else {
			uids, err := r.tenantMemberIDs(ctx, d.tenant)
			if err != nil {
				return nil, err
			}
			aids, err := r.Ent.Agent.Query().Where(agent.TenantID(d.tenant)).IDs(ctx)
			if err != nil {
				return nil, err
			}
			q = q.Where(requestlog.Or(requestlog.UserIDIn(uids...), requestlog.AgentIDIn(aids...)))
		}
	}
	total, err := q.Clone().Count(ctx)
	if err != nil {
		return nil, err
	}
	limit, offset := pageBounds(page)
	rows, err := q.Order(orderNewest).Limit(limit).Offset(offset).All(ctx)
	if err != nil {
		return nil, err
	}
	return &model.RequestLogConnection{Items: mapSlice(rows, toModelRequestLog), Total: total}, nil
}

// RequestMetrics returns windowed, gap-filled request-traffic metrics bucketed
// by the requested granularity. The heavy lifting (validation, tenant scoping,
// pushed-down aggregation, gap-fill) lives in requestmetrics.go to keep this
// resolver file focused.
func (r *queryResolver) RequestMetrics(ctx context.Context, from time.Time, to time.Time, granularity model.RequestMetricsBucketGranularity, filter *model.RequestMetricsFilter) (*model.RequestMetrics, error) {
	return r.requestMetrics(ctx, from, to, granularity, filter)
}

// GatewayHealth is the resolver for the gatewayHealth field.
func (r *queryResolver) GatewayHealth(ctx context.Context) ([]model.GatewayHealth, error) {
	return r.Resolver.gatewayHealth(ctx)
}
