package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"strings"

	"github.com/VMware-AI/agent-platform-backend/internal/auth"
	"github.com/VMware-AI/agent-platform-backend/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// UpdatePlatformSettings is the resolver for the updatePlatformSettings field.
func (r *mutationResolver) UpdatePlatformSettings(ctx context.Context, input model.UpdatePlatformSettingsInput) (*model.PlatformSettings, error) {
	if input.AgentUser != nil {
		v := strings.TrimSpace(*input.AgentUser)
		if v == "" {
			return nil, gqlerror.Errorf("agentUser must not be empty")
		}
		if err := r.setSetting(ctx, settingKeyAgentUser, v); err != nil {
			return nil, err
		}
		r.audit(ctx, "platform_settings.update", "setting", settingKeyAgentUser, true, actorID(auth.FromContext(ctx)))
	}
	if input.PackageSourceURL != nil {
		v := strings.TrimSpace(*input.PackageSourceURL)
		if v != "" { // empty clears the setting; anything else must be a usable mirror URL
			if err := validatePackageSourceURL(v); err != nil {
				return nil, gqlerror.Errorf("%v", err)
			}
		}
		if err := r.setSetting(ctx, settingKeyAgentPkgURL, v); err != nil {
			return nil, err
		}
	}
	if input.PackageSourceUser != nil {
		if err := r.setSetting(ctx, settingKeyAgentPkgUser, strings.TrimSpace(*input.PackageSourceUser)); err != nil {
			return nil, err
		}
	}
	if input.PackageSourcePassword != nil {
		if err := r.setPackageSourcePassword(ctx, *input.PackageSourcePassword); err != nil {
			return nil, err
		}
	}
	if input.PackageSourceURL != nil || input.PackageSourceUser != nil || input.PackageSourcePassword != nil {
		r.audit(ctx, "platform_settings.update", "setting", "agent_pkg_source", true, actorID(auth.FromContext(ctx)))
	}
	return &model.PlatformSettings{
		AgentUser:         r.getSetting(ctx, settingKeyAgentUser, defaultAgentUser),
		PackageSourceURL:  r.getSetting(ctx, settingKeyAgentPkgURL, ""),
		PackageSourceUser: r.getSetting(ctx, settingKeyAgentPkgUser, ""),
	}, nil
}

// PlatformSettings is the resolver for the platformSettings field.
func (r *queryResolver) PlatformSettings(ctx context.Context) (*model.PlatformSettings, error) {
	return &model.PlatformSettings{
		AgentUser:         r.getSetting(ctx, settingKeyAgentUser, defaultAgentUser),
		PackageSourceURL:  r.getSetting(ctx, settingKeyAgentPkgURL, ""),
		PackageSourceUser: r.getSetting(ctx, settingKeyAgentPkgUser, ""),
	}, nil
}
