package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
	"log"
	"regexp"
	"strconv"
	"time"

	"github.com/VMware-AI/agent-platform-backend/ent"
	"github.com/VMware-AI/agent-platform-backend/ent/virtualkey"
	"github.com/VMware-AI/agent-platform-backend/internal/auth"
	"github.com/VMware-AI/agent-platform-backend/internal/gateway"
	"github.com/VMware-AI/agent-platform-backend/internal/graph/model"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// durationRE matches forms like "30d", "12h", "2w", "90m".
var durationRE = regexp.MustCompile(`^(\d+)([dhwm])$`)

// parseDuration returns time.Duration for "Nd"/"Nh"/"Nw"/"Nm" forms.
// Returns (0, false) when the input does not match.
func parseDuration(s string) (time.Duration, bool) {
	m := durationRE.FindStringSubmatch(s)
	if m == nil {
		return 0, false
	}
	n, _ := strconv.Atoi(m[1])
	switch m[2] {
	case "d":
		return time.Duration(n) * 24 * time.Hour, true
	case "h":
		return time.Duration(n) * time.Hour, true
	case "w":
		return time.Duration(n) * 7 * 24 * time.Hour, true
	case "m":
		return time.Duration(n) * 30 * 24 * time.Hour, true
	}
	return 0, false
}

// vkDerefBool returns *p if non-nil, else def. (Renamed to avoid collision
// with the same-named helper in model_spec.go.)
func vkDerefBool(p *bool, def bool) bool {
	if p == nil {
		return def
	}
	return *p
}

// vkDerefStr returns *p if non-nil+non-empty, else def.
func vkDerefStr(p *string, def string) string {
	if p == nil || *p == "" {
		return def
	}
	return *p
}

// vkDerefFloat64 returns *p if non-nil, else def.
func vkDerefFloat64(p *float64, def float64) float64 {
	if p == nil {
		return def
	}
	return *p
}

// vkDerefInt returns *p if non-nil, else def.
func vkDerefInt(p *int, def int) int {
	if p == nil {
		return def
	}
	return *p
}

// redactKey is a local copy of gateway.redactKey (which is unexported).
// Used to populate masked_key on VirtualKey at Issue / Regenerate.
// Format: head 6 + "..." + tail 4; < 12 chars returned verbatim.
func redactKey(plain string) string {
	if len(plain) < 12 {
		return plain
	}
	return plain[:6] + "..." + plain[len(plain)-4:]
}

// IssueVirtualKey creates a new LiteLLM key for an organization, bound to
// exactly one modelGateway (the one the operator picked). The plaintext
// secret is returned ONCE in the IssuedVirtualKey wrapper; subsequent
// reads see only maskedKey.
//
// Routing path: input.ModelGateway → GatewayConnection.Get → build client.
// Step 4 performs a real-time cross-check against the gateway's live model
// list before mint — this is the model↔modelGateway strong-coupling
// invariant. Compensating gw.DeleteKey on DB persist failure prevents
// orphans at the gateway side.
func (r *mutationResolver) IssueVirtualKey(ctx context.Context, input model.IssueVirtualKeyInput) (*model.IssuedVirtualKey, error) {
	if input.OrganizationID == "" {
		return nil, gqlerror.Errorf("organizationId is required")
	}
	if input.Name == "" {
		return nil, gqlerror.Errorf("name is required")
	}
	if input.ModelGateway == "" {
		return nil, gqlerror.Errorf("modelGateway is required")
	}

	// 1) Direct gateway lookup by id (replaces the prior
	//    team→department→gateway derivation).
	mgID, err := uuid.Parse(input.ModelGateway)
	if err != nil {
		return nil, gqlerror.Errorf("invalid modelGateway")
	}
	gwConn, err := r.Ent.GatewayConnection.Get(ctx, mgID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, gqlerror.Errorf("model gateway not found")
		}
		return nil, err
	}
	gw := r.buildGatewayKeyClient(ctx, gwConn)
	if gw == nil {
		return nil, gqlerror.Errorf("model gateway client unavailable for gateway %q", input.ModelGateway)
	}

	// 2) Optional agent pre-bind (1:1 invariant checked here; DB partial
	//    unique index is the authoritative race gate).
	var agentID *uuid.UUID
	if input.AgentID != nil {
		aID, err := uuid.Parse(*input.AgentID)
		if err != nil {
			return nil, gqlerror.Errorf("invalid agentId")
		}
		existing, qerr := r.Ent.VirtualKey.Query().
			Where(virtualkey.AgentIDEQ(aID), virtualkey.StatusNEQ(virtualkey.StatusRevoked)).
			First(ctx)
		if qerr == nil && existing != nil {
			return nil, gqlerror.Errorf("agent %s already has active key %s", aID, existing.ID)
		}
		if qerr != nil && !ent.IsNotFound(qerr) {
			return nil, qerr
		}
		agentID = &aID
	}

	// 3) Resolve expiry: duration > expiresAt (logged once).
	var expiresAt *time.Time
	if input.Duration != nil && *input.Duration != "" {
		d, ok := parseDuration(*input.Duration)
		if !ok {
			return nil, gqlerror.Errorf("invalid duration format %q (expected <n>d|h|w|m)", *input.Duration)
		}
		t := time.Now().Add(d)
		expiresAt = &t
	} else if input.ExpiresAt != nil {
		expiresAt = input.ExpiresAt
	}

	// 4) Cross-check: every model in input.Models must be in the live
	//    model list of the gateway (gatewayAvailableModels, real-time, no
	//    cache). Backend-call 400s when the operator passed stale names.
	if len(input.Models) > 0 {
		available, lerr := gw.ListAvailableModels(ctx)
		if lerr != nil {
			return nil, fmt.Errorf("list available models from gateway: %w", lerr)
		}
		known := make(map[string]struct{}, len(available))
		for _, m := range available {
			known[m] = struct{}{}
		}
		var stale []string
		for _, m := range input.Models {
			if _, ok := known[m]; !ok {
				stale = append(stale, m)
			}
		}
		if len(stale) > 0 {
			return nil, gqlerror.Errorf("models not available on modelGateway %s: %v", input.ModelGateway, stale)
		}
	}

	// 5) Build gateway request. Field names match the regenerated
	// gateway.GenerateKeyRequest (see internal/gateway/client.go).
	gReq := gateway.GenerateKeyRequest{
		OrganizationID:      input.OrganizationID,
		Models:              input.Models,
		MaxBudget:           input.MaxBudget,
		BudgetDuration:      vkDerefStr(input.BudgetDuration, ""),
		MaxParallelRequests: input.MaxParallelRequests,
		RPMLimit:            input.RpmLimit,
		TPMLimit:            input.TpmLimit,
		RPMLimitType:        vkDerefStr(input.RpmLimitType, ""),
		TPMLimitType:        vkDerefStr(input.TpmLimitType, ""),
		AllowedRoutes:       input.AllowedRoutes,
		Tags:                input.Tags,
		Blocked:             input.Blocked,
		KeyType:             vkDerefStr(input.KeyType, ""),
		AutoRotate:          input.AutoRotate,
		RotationInterval:    vkDerefStr(input.RotationInterval, ""),
	}
	// AgentID and ExpiresAt are not in the current gateway.GenerateKeyRequest
	// struct (in-flight gateway/client.go rewrite). The platform persists them
	// to its own row regardless, so this is wire-side inert. Follow-up:
	// extend GenerateKeyRequest and re-enable these passes once the gateway
	// client settles.
	_ = agentID
	_ = expiresAt

	resp, err := gw.GenerateKey(ctx, gReq)
	if err != nil {
		r.audit(ctx, "key.issue", "virtual_key", "", false, actorID(auth.FromContext(ctx)))
		return nil, fmt.Errorf("gateway mint: %w", err)
	}

	// 6) Persist governance row.
	create := r.Ent.VirtualKey.Create().
		SetLitellmKey(resp.Key).
		SetLitellmToken(resp.Token).
		SetMaskedKey(redactKey(resp.Key)).
		SetName(input.Name).
		SetOrganizationID(input.OrganizationID).
		SetModelGatewayID(mgID).
		SetModels(input.Models).
		SetMaxBudget(vkDerefFloat64(input.MaxBudget, 0)).
		SetMaxParallelRequests(vkDerefInt(input.MaxParallelRequests, 0)).
		SetTpmLimit(vkDerefInt(input.TpmLimit, 0)).
		SetRpmLimit(vkDerefInt(input.RpmLimit, 0)).
		SetTpmLimitType(vkDerefStr(input.TpmLimitType, "")).
		SetRpmLimitType(vkDerefStr(input.RpmLimitType, "")).
		SetBudgetDuration(vkDerefStr(input.BudgetDuration, "")).
		SetTags(input.Tags).
		SetAllowedRoutes(input.AllowedRoutes).
		SetBlocked(vkDerefBool(input.Blocked, false)).
		SetKeyType(vkDerefStr(input.KeyType, "default")).
		SetAutoRotate(vkDerefBool(input.AutoRotate, false)).
		SetRotationInterval(vkDerefStr(input.RotationInterval, ""))
	if expiresAt != nil {
		create = create.SetExpiresAt(*expiresAt)
	}
	if agentID != nil {
		create = create.SetAgentID(*agentID)
	}

	vk, err := create.Save(ctx)
	if err != nil {
		// Compensating revoke on gateway (detached context: original may
		// already be canceled/timed-out).
		cctx := context.WithoutCancel(ctx)
		if derr := gw.DeleteKey(cctx, resp.Key); derr != nil {
			log.Printf("compensating gw.DeleteKey failed: %v", derr)
		}
		r.audit(ctx, "key.issue", "virtual_key", "", false, actorID(auth.FromContext(ctx)))
		return nil, fmt.Errorf("persist virtual_key: %w", err)
	}

	r.audit(ctx, "key.issue", "virtual_key", vk.ID.String(), true, actorID(auth.FromContext(ctx)))

	mapped, merr := toModelVirtualKey(ctx, r.Resolver, vk)
	if merr != nil {
		return nil, merr
	}
	return &model.IssuedVirtualKey{
		VirtualKey: mapped,
		Secret:     resp.Key,
	}, nil
}

// RevokeVirtualKey disables a key at the gateway FIRST, then flips the DB
// row to status=revoked (terminal). See spec §1.1 invariant #3.
func (r *mutationResolver) RevokeVirtualKey(ctx context.Context, id string) (bool, error) {
	vkID, err := uuid.Parse(id)
	if err != nil {
		return false, gqlerror.Errorf("invalid id")
	}
	vk, err := r.Ent.VirtualKey.Get(ctx, vkID)
	if err != nil {
		return false, err
	}
	gw := r.modelGatewayClientForVK(ctx, vk)
	if gw == nil {
		return false, gqlerror.Errorf("model gateway is not configured; key not revoked at gateway")
	}
	if err := gw.DeleteKey(ctx, vk.LitellmKey); err != nil {
		return false, fmt.Errorf("gateway: %w", err)
	}
	if _, err := r.Ent.VirtualKey.UpdateOne(vk).SetStatus(virtualkey.StatusRevoked).Save(ctx); err != nil {
		return false, err
	}
	r.audit(ctx, "key.revoke", "virtual_key", vkID.String(), true, actorID(auth.FromContext(ctx)))
	return true, nil
}

// RegenerateVirtualKey rotates the secret at the gateway AND keeps the
// governance row intact. The masked_key is rewritten in lock-step with the
// new secret (spec §3.2). The new plaintext is returned ONCE. Persist runs
// under context.WithoutCancel so a client cancel cannot drop the rotation.
func (r *mutationResolver) RegenerateVirtualKey(ctx context.Context, id string) (*model.IssuedVirtualKey, error) {
	vkID, err := uuid.Parse(id)
	if err != nil {
		return nil, gqlerror.Errorf("invalid id")
	}
	vk, err := r.Ent.VirtualKey.Get(ctx, vkID)
	if err != nil {
		return nil, err
	}
	if vk.Status == virtualkey.StatusRevoked {
		return nil, gqlerror.Errorf("key is revoked and cannot be regenerated")
	}
	gw := r.modelGatewayClientForVK(ctx, vk)
	if gw == nil {
		return nil, gqlerror.Errorf("model gateway is not configured; key not regenerated at gateway")
	}
	resp, err := gw.RegenerateKey(ctx, vk.LitellmKey)
	if err != nil {
		r.audit(ctx, "key.regenerate", "virtual_key", vkID.String(), false, actorID(auth.FromContext(ctx)))
		return nil, fmt.Errorf("gateway regenerate: %w", err)
	}
	updated, err := r.Ent.VirtualKey.UpdateOneID(vkID).
		SetLitellmKey(resp.Key).
		SetLitellmToken(resp.Token).
		SetMaskedKey(redactKey(resp.Key)).
		Save(context.WithoutCancel(ctx))
	if err != nil {
		r.audit(ctx, "key.regenerate", "virtual_key", vkID.String(), false, actorID(auth.FromContext(ctx)))
		return nil, fmt.Errorf("persist regenerated virtual_key: %w", err)
	}
	r.audit(ctx, "key.regenerate", "virtual_key", vkID.String(), true, actorID(auth.FromContext(ctx)))
	mapped, merr := toModelVirtualKey(ctx, r.Resolver, updated)
	if merr != nil {
		return nil, merr
	}
	return &model.IssuedVirtualKey{
		VirtualKey: mapped,
		Secret:     resp.Key,
	}, nil
}

// SetVirtualKeyEnabled toggles active/disabled (NOT revoke — see spec
// §1.1 invariant). Gateway-first ordering preserved.
func (r *mutationResolver) SetVirtualKeyEnabled(ctx context.Context, id string, enabled bool) (*model.VirtualKey, error) {
	vkID, err := uuid.Parse(id)
	if err != nil {
		return nil, gqlerror.Errorf("invalid id")
	}
	vk, err := r.Ent.VirtualKey.Get(ctx, vkID)
	if err != nil {
		return nil, err
	}
	if vk.Status == virtualkey.StatusRevoked {
		return nil, gqlerror.Errorf("key is revoked and cannot be re-enabled")
	}
	gw := r.modelGatewayClientForVK(ctx, vk)
	if gw == nil {
		return nil, gqlerror.Errorf("model gateway is not configured; key not updated at gateway")
	}
	blocked := !enabled
	if err := gw.UpdateKey(ctx, gateway.UpdateKeyRequest{Key: vk.LitellmKey, Blocked: &blocked}); err != nil {
		return nil, fmt.Errorf("gateway update: %w", err)
	}
	status := virtualkey.StatusActive
	if !enabled {
		status = virtualkey.StatusDisabled
	}
	updated, err := r.Ent.VirtualKey.UpdateOne(vk).SetStatus(status).Save(ctx)
	if err != nil {
		return nil, err
	}
	r.audit(ctx, "key.set_enabled", "virtual_key", vkID.String(), true, actorID(auth.FromContext(ctx)))
	return toModelVirtualKey(ctx, r.Resolver, updated)
}

// AssociateVirtualKeyAgent binds (or rebinds) an existing key to an agent.
// Enforces the 1:1 active-key-per-agent invariant (DB partial unique index
// is the authoritative race gate; pre-check provides a clean 409).
func (r *mutationResolver) AssociateVirtualKeyAgent(ctx context.Context, virtualKeyID string, agentID string) (*model.VirtualKey, error) {
	vkID, err := uuid.Parse(virtualKeyID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid virtualKeyId")
	}
	aID, err := uuid.Parse(agentID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid agentId")
	}
	if _, err := r.Ent.VirtualKey.Get(ctx, vkID); err != nil {
		return nil, err
	}
	existing, qerr := r.Ent.VirtualKey.Query().
		Where(virtualkey.AgentIDEQ(aID), virtualkey.StatusNEQ(virtualkey.StatusRevoked)).
		First(ctx)
	if qerr == nil && existing != nil && existing.ID != vkID {
		return nil, gqlerror.Errorf("agent %s already has active key %s", aID, existing.ID)
	}
	if qerr != nil && !ent.IsNotFound(qerr) {
		return nil, qerr
	}
	updated, err := r.Ent.VirtualKey.UpdateOneID(vkID).SetAgentID(aID).Save(ctx)
	if err != nil {
		return nil, err
	}
	r.audit(ctx, "key.associate_agent", "virtual_key", vkID.String(), true, actorID(auth.FromContext(ctx)))
	return toModelVirtualKey(ctx, r.Resolver, updated)
}

// GatewayAvailableModels returns the live model list advertised by the
// given modelGateway. Real-time: every call hits LiteLLM /model/list on
// demand (no cache). Used by the operator-console issue form to populate
// the "Models" multi-select after the operator picks a modelGateway.
func (r *queryResolver) GatewayAvailableModels(ctx context.Context, gatewayConnectionID string) ([]string, error) {
	mgID, err := uuid.Parse(gatewayConnectionID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid gatewayConnectionId")
	}
	conn, err := r.Ent.GatewayConnection.Get(ctx, mgID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, gqlerror.Errorf("model gateway not found")
		}
		return nil, err
	}
	gw := r.buildGatewayKeyClient(ctx, conn)
	if gw == nil {
		return nil, gqlerror.Errorf("model gateway client unavailable")
	}
	return gw.ListAvailableModels(ctx)
}

// VirtualKeys lists keys with three optional filters: organizationId,
// agentId, modelGateway. All null → all keys in current tenant. Multiple
// set → intersection. Secrets are never returned (only maskedKey on each
// row).
func (r *queryResolver) VirtualKeys(ctx context.Context, organizationID *string, agentID *string, modelGateway *string) ([]model.VirtualKey, error) {
	q := r.Ent.VirtualKey.Query()
	if organizationID != nil {
		q = q.Where(virtualkey.OrganizationIDEQ(*organizationID))
	}
	if agentID != nil {
		aID, err := uuid.Parse(*agentID)
		if err != nil {
			return nil, gqlerror.Errorf("invalid agentId")
		}
		q = q.Where(virtualkey.AgentIDEQ(aID))
	}
	if modelGateway != nil {
		mgID, err := uuid.Parse(*modelGateway)
		if err != nil {
			return nil, gqlerror.Errorf("invalid modelGateway")
		}
		q = q.Where(virtualkey.ModelGatewayIDEQ(mgID))
	}
	// TODO(follow-up): replace this denyAll fallback with a real
	// organizationId → tenant resolution (see spec §3.4 + §7 follow-ups).
	if d := tenantScopeFor(ctx); d.apply && d.denyAll {
		q = q.Where(virtualkey.OrganizationIDEQ("")) // impossible match
	}
	keys, err := q.Order(orderNewest).All(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.VirtualKey, 0, len(keys))
	for _, k := range keys {
		mapped, merr := toModelVirtualKey(ctx, r.Resolver, k)
		if merr != nil {
			return nil, merr
		}
		out = append(out, *mapped)
	}
	return out, nil
}
