// Code generated by ent, DO NOT EDIT.

package agentheartbeat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/VMware-AI/agent-platform-backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLTE(FieldID, id))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldAgentID, v))
}

// ReportedAt applies equality check predicate on the "reported_at" field. It's identical to ReportedAtEQ.
func ReportedAt(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldReportedAt, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldReceivedAt, v))
}

// AgentVersion applies equality check predicate on the "agent_version" field. It's identical to AgentVersionEQ.
func AgentVersion(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldAgentVersion, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v uuid.UUID) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLTE(FieldAgentID, v))
}

// ReportedAtEQ applies the EQ predicate on the "reported_at" field.
func ReportedAtEQ(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldReportedAt, v))
}

// ReportedAtNEQ applies the NEQ predicate on the "reported_at" field.
func ReportedAtNEQ(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNEQ(FieldReportedAt, v))
}

// ReportedAtIn applies the In predicate on the "reported_at" field.
func ReportedAtIn(vs ...time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIn(FieldReportedAt, vs...))
}

// ReportedAtNotIn applies the NotIn predicate on the "reported_at" field.
func ReportedAtNotIn(vs ...time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotIn(FieldReportedAt, vs...))
}

// ReportedAtGT applies the GT predicate on the "reported_at" field.
func ReportedAtGT(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGT(FieldReportedAt, v))
}

// ReportedAtGTE applies the GTE predicate on the "reported_at" field.
func ReportedAtGTE(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGTE(FieldReportedAt, v))
}

// ReportedAtLT applies the LT predicate on the "reported_at" field.
func ReportedAtLT(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLT(FieldReportedAt, v))
}

// ReportedAtLTE applies the LTE predicate on the "reported_at" field.
func ReportedAtLTE(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLTE(FieldReportedAt, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLTE(FieldReceivedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotIn(FieldStatus, vs...))
}

// AgentVersionEQ applies the EQ predicate on the "agent_version" field.
func AgentVersionEQ(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldAgentVersion, v))
}

// AgentVersionNEQ applies the NEQ predicate on the "agent_version" field.
func AgentVersionNEQ(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNEQ(FieldAgentVersion, v))
}

// AgentVersionIn applies the In predicate on the "agent_version" field.
func AgentVersionIn(vs ...string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIn(FieldAgentVersion, vs...))
}

// AgentVersionNotIn applies the NotIn predicate on the "agent_version" field.
func AgentVersionNotIn(vs ...string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotIn(FieldAgentVersion, vs...))
}

// AgentVersionGT applies the GT predicate on the "agent_version" field.
func AgentVersionGT(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGT(FieldAgentVersion, v))
}

// AgentVersionGTE applies the GTE predicate on the "agent_version" field.
func AgentVersionGTE(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldGTE(FieldAgentVersion, v))
}

// AgentVersionLT applies the LT predicate on the "agent_version" field.
func AgentVersionLT(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLT(FieldAgentVersion, v))
}

// AgentVersionLTE applies the LTE predicate on the "agent_version" field.
func AgentVersionLTE(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldLTE(FieldAgentVersion, v))
}

// AgentVersionContains applies the Contains predicate on the "agent_version" field.
func AgentVersionContains(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldContains(FieldAgentVersion, v))
}

// AgentVersionHasPrefix applies the HasPrefix predicate on the "agent_version" field.
func AgentVersionHasPrefix(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldHasPrefix(FieldAgentVersion, v))
}

// AgentVersionHasSuffix applies the HasSuffix predicate on the "agent_version" field.
func AgentVersionHasSuffix(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldHasSuffix(FieldAgentVersion, v))
}

// AgentVersionIsNil applies the IsNil predicate on the "agent_version" field.
func AgentVersionIsNil() predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIsNull(FieldAgentVersion))
}

// AgentVersionNotNil applies the NotNil predicate on the "agent_version" field.
func AgentVersionNotNil() predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotNull(FieldAgentVersion))
}

// AgentVersionEqualFold applies the EqualFold predicate on the "agent_version" field.
func AgentVersionEqualFold(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEqualFold(FieldAgentVersion, v))
}

// AgentVersionContainsFold applies the ContainsFold predicate on the "agent_version" field.
func AgentVersionContainsFold(v string) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldContainsFold(FieldAgentVersion, v))
}

// RotationStateEQ applies the EQ predicate on the "rotation_state" field.
func RotationStateEQ(v RotationState) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldEQ(FieldRotationState, v))
}

// RotationStateNEQ applies the NEQ predicate on the "rotation_state" field.
func RotationStateNEQ(v RotationState) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNEQ(FieldRotationState, v))
}

// RotationStateIn applies the In predicate on the "rotation_state" field.
func RotationStateIn(vs ...RotationState) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIn(FieldRotationState, vs...))
}

// RotationStateNotIn applies the NotIn predicate on the "rotation_state" field.
func RotationStateNotIn(vs ...RotationState) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotIn(FieldRotationState, vs...))
}

// RotationStateIsNil applies the IsNil predicate on the "rotation_state" field.
func RotationStateIsNil() predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIsNull(FieldRotationState))
}

// RotationStateNotNil applies the NotNil predicate on the "rotation_state" field.
func RotationStateNotNil() predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotNull(FieldRotationState))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.FieldNotNull(FieldDetail))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentHeartbeat) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentHeartbeat) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentHeartbeat) predicate.AgentHeartbeat {
	return predicate.AgentHeartbeat(sql.NotPredicates(p))
}
