// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// AgentConfig is the predicate function for agentconfig builders.
type AgentConfig func(*sql.Selector)

// AgentEnrollment is the predicate function for agentenrollment builders.
type AgentEnrollment func(*sql.Selector)

// AgentHeartbeat is the predicate function for agentheartbeat builders.
type AgentHeartbeat func(*sql.Selector)

// AgentTemplate is the predicate function for agenttemplate builders.
type AgentTemplate func(*sql.Selector)

// Artifact is the predicate function for artifact builders.
type Artifact func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Environment is the predicate function for environment builders.
type Environment func(*sql.Selector)

// GatewayConnection is the predicate function for gatewayconnection builders.
type GatewayConnection func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Membership is the predicate function for membership builders.
type Membership func(*sql.Selector)

// ModelRoute is the predicate function for modelroute builders.
type ModelRoute func(*sql.Selector)

// OvaTemplateFamily is the predicate function for ovatemplatefamily builders.
type OvaTemplateFamily func(*sql.Selector)

// OvaTemplateVersion is the predicate function for ovatemplateversion builders.
type OvaTemplateVersion func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// PlatformSecret is the predicate function for platformsecret builders.
type PlatformSecret func(*sql.Selector)

// RateLimitPolicy is the predicate function for ratelimitpolicy builders.
type RateLimitPolicy func(*sql.Selector)

// RequestLog is the predicate function for requestlog builders.
type RequestLog func(*sql.Selector)

// ResourcePool is the predicate function for resourcepool builders.
type ResourcePool func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RotationCommand is the predicate function for rotationcommand builders.
type RotationCommand func(*sql.Selector)

// RouterTier is the predicate function for routertier builders.
type RouterTier func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TokenUsage is the predicate function for tokenusage builders.
type TokenUsage func(*sql.Selector)

// Upstream is the predicate function for upstream builders.
type Upstream func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VirtualKey is the predicate function for virtualkey builders.
type VirtualKey func(*sql.Selector)
